# -*- coding: utf-8 -*-
# Contenido derivado del video "What is a backend?" (Backend Engineering,
# youtube.com/watch?v=6Ss4dJD9Kzg): el recorrido fisico de una peticion
# (DNS -> firewall -> nginx -> proceso) y por que la logica de backend
# no puede vivir en el navegador.
# Misma metodologia de ejes que frontend/backend/data/flask/python/pandas/fastapi.
NAME = "Anatomia del Backend"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Quiero entender que ES exactamente un backend", [
    ("La maquina que esta escuchando peticiones por un puerto abierto",
     "servidor (backend)"),
    ("Los protocolos por los que puede escuchar",
     "HTTP, WebSocket, gRPC..."),
    ("El puerto por el que entra trafico web sin cifrar",
     "80 (HTTP)"),
    ("El puerto por el que entra trafico cifrado",
     "443 (HTTPS)"),
    ("Lo que devuelve al cliente",
     "contenido: estaticos (HTML, JS, imagenes) o JSON"),
    ("Por que se llama SERVIDOR",
     "porque SIRVE contenido; y ademas acepta datos que le mandan"),
  ]),
  ("Quiero saber como mi peticion encuentra la maquina correcta", [
    ("Traducir un nombre de dominio a una maquina concreta",
     "servidor DNS"),
    ("El registro que apunta un nombre a una IP",
     "registro A"),
    ("El registro que apunta un nombre a OTRO dominio o subdominio",
     "registro CNAME"),
    ("El prefijo delante del dominio (backend-demo.sitio.xyz)",
     "subdominio"),
    ("La direccion a la que resuelve ese registro A",
     "la IP publica de la instancia (EC2 en AWS)"),
  ]),
  ("Quiero saber que pasa ANTES de entrar a la maquina", [
    ("La capa que decide que trafico puede entrar a la instancia",
     "firewall (security group de AWS)"),
    ("Dejar pasar trafico cifrado",
     "abrir el puerto 443"),
    ("Dejar pasar trafico sin cifrar",
     "abrir el puerto 80"),
    ("Poder entrar a la maquina por terminal a administrarla",
     "abrir el puerto 22 (SSH)"),
    ("Que ocurre si el puerto NO esta permitido",
     "AWS bloquea ahi: la peticion nunca llega al servidor"),
  ]),
  ("Quiero un unico punto de entrada delante de mis servidores", [
    ("Un servidor que se sienta DELANTE de otros servidores",
     "reverse proxy (nginx)"),
    ("Manejar redirects y configuracion desde un sitio central",
     "la config de nginx (en vez de tocar cada servidor)"),
    ("Declarar a que dominio responde un bloque de config",
     "server_name (p.ej. backend-demo.sitio.xyz)"),
    ("Mandar el trafico de ese dominio al servidor interno",
     "reenviar a localhost:3001 (el puerto donde corre node)"),
    ("Conseguir y renovar el certificado SSL solo",
     "certbot"),
    ("Que quien llegue por HTTP acabe en HTTPS",
     "escuchar el 80 y redirigir al 443"),
  ]),
  ("Quiero que mi servidor siga vivo dentro de la maquina", [
    ("Mantener el proceso corriendo y reiniciarlo si cae",
     "gestor de procesos (pm2)"),
    ("Ver que procesos hay corriendo",
     "pm2 list"),
    ("Donde corre de verdad el backend dentro de la instancia",
     "localhost:3001 (el proceso node)"),
    ("Donde corre el frontend en esa misma instancia",
     "localhost:3000 (el proceso next)"),
    ("Comprobar el servidor desde dentro de la maquina, sin navegador",
     "curl localhost:3001/users"),
  ]),
  ("Quiero trazar el camino completo de una peticion", [
    ("Donde empieza",
     "el navegador (el cliente)"),
    ("Primer salto: quien resuelve el nombre",
     "DNS -> devuelve la IP publica"),
    ("Segundo salto: quien filtra la entrada",
     "el firewall / security group (puertos permitidos)"),
    ("Tercer salto: quien recibe dentro de la maquina",
     "nginx (reverse proxy)"),
    ("Cuarto salto: a quien se lo entrega nginx",
     "al proceso en localhost:3001"),
    ("Por que en desarrollo no ves ninguno de esos saltos",
     "en local vas directo a localhost:3000/users; los saltos son del deploy"),
  ]),
  ("Quiero saber PARA QUE sirve un backend de verdad", [
    ("Que la accion del usuario sobreviva al cierre de la app",
     "persistirla (guardarla en una base de datos)"),
    ("Saber QUIEN hizo la accion",
     "identificar al usuario por su id en la peticion"),
    ("Avisar a OTRO usuario de lo que paso",
     "disparar una notificacion hacia ese otro id"),
    ("Tener el estado de TODOS los usuarios en un solo sitio",
     "servidor centralizado (cada cliente solo ve su parte)"),
    ("La responsabilidad del backend resumida en una palabra",
     "DATOS: traerlos, recibirlos y persistirlos"),
  ]),
  ("Quiero entender como carga una pagina de frontend", [
    ("Lo primero que pide el navegador",
     "el documento HTML"),
    ("Lo que pide despues, en peticiones separadas",
     "JS, CSS, fuentes e imagenes (un request por recurso)"),
    ("Lo que ocurre cuando llegan los CSS",
     "el navegador PINTA la pagina (estilos, fondo, tipografia)"),
    ("Lo que ocurre cuando llega el JavaScript",
     "hidratacion: se enganchan los event listeners y los botones responden"),
    ("Donde se ejecuta ese JavaScript",
     "en el navegador del usuario (el navegador es el runtime)"),
    ("En que se diferencia del backend",
     "el back PROCESA y manda el resultado; el front manda CODIGO y el navegador lo corre"),
  ]),
  ("Quiero saber por que la logica de backend no puede vivir en el navegador", [
    ("El entorno aislado del sistema operativo, procesos y archivos",
     "sandbox del navegador"),
    ("Lo unico a lo que ese codigo puede acceder",
     "el DOM, APIs del navegador (localStorage, cookies) y APIs externas permitidas"),
    ("Escribir un log o leer variables de entorno",
     "imposible: no hay acceso al sistema de archivos (razon de SEGURIDAD)"),
    ("Llamar a una API de otro dominio",
     "bloqueado por CORS salvo que esa API mande los headers adecuados"),
    ("Hablar con la base de datos",
     "hace falta un driver nativo (pg, mongodb) con conexiones persistentes"),
    ("Evitar abrir y cerrar conexion en cada peticion",
     "connection pool (lista de conexiones reutilizadas)"),
    ("Correr logica pesada sin depender del aparato del usuario",
     "un servidor centralizado al que le subes CPU y RAM cuando quieras"),
  ]),
]

# INTEGRADOR: de las SENALES concretas (discriminadores) al concepto + tip verbalizable.
ESTACIONES = [
  ("QUE ES UN BACKEND", [
    ("Es una computadora escuchando peticiones por un puerto abierto",
     "Es accesible por internet, asi que clientes y otros front ends le llegan",
     "Sirve contenido (estaticos o JSON) y ademas acepta datos que le mandan",
     "Servidor backend",
     "un backend es una computadora escuchando en un puerto abierto que sirve y recibe datos"),
    ("HTTP es el patron clasico de peticion y respuesta",
     "WebSocket mantiene la conexion abierta en los dos sentidos",
     "gRPC es otro protocolo de llamadas, sobre todo entre servicios",
     "Protocolos que escucha",
     "no todo backend es HTTP: websocket y grpc entran por el mismo tipo de puerta"),
    ("El 80 es trafico web SIN cifrar (HTTP)",
     "El 443 es trafico CIFRADO (HTTPS)",
     "El 22 no es para usuarios: es SSH, para administrar la maquina",
     "Puertos 80 / 443 / 22",
     "80 abierto, 443 cifrado, 22 es la puerta de servicio"),
  ]),
  ("DNS: DEL NOMBRE A LA MAQUINA", [
    ("El DNS traduce un nombre de dominio a una maquina",
     "El registro A apunta un nombre a una IP concreta",
     "El registro CNAME apunta un nombre a OTRO dominio o subdominio",
     "Registro A vs CNAME",
     "A apunta a una IP; CNAME apunta a otro nombre"),
    ("backend-demo.sitio.xyz: 'sitio.xyz' es el dominio",
     "'backend-demo' delante es el subdominio",
     "Cada subdominio puede tener su propio registro y apuntar a otro sitio",
     "Dominio vs subdominio",
     "el subdominio es el prefijo: mismo dominio, destino distinto"),
  ]),
  ("EL FIREWALL", [
    ("Antes de entrar a la maquina, la peticion pasa por el firewall",
     "En AWS eso es el security group asignado a la instancia",
     "Ahi declaras QUE puertos quedan accesibles desde internet",
     "Firewall / security group",
     "el firewall decide que puertos existen para el mundo"),
    ("Si no abres el 443, el trafico HTTPS muere ahi",
     "Si no abres el 80, el trafico HTTP muere ahi",
     "El servidor puede estar perfecto y aun asi no recibir nada",
     "Puerto cerrado",
     "si el puerto no esta permitido, AWS bloquea antes de llegar al servidor"),
  ]),
  ("NGINX: EL REVERSE PROXY", [
    ("Es un servidor que se sienta DELANTE de otros servidores",
     "Centraliza redirects y configuracion en un solo sitio",
     "Asi no tocas la config de cada servidor por separado",
     "Reverse proxy",
     "el reverse proxy es el recepcionista: recibe todo y reparte hacia dentro"),
    ("server_name declara a que dominio responde ese bloque",
     "El trafico de ese dominio se reenvia a un puerto interno (localhost:3001)",
     "El mismo nginx manda otro dominio al 3000 (el frontend)",
     "server_name y reenvio",
     "server_name dice de quien es el trafico; el reenvio dice a que puerto va"),
    ("Escucha el puerto 80 y redirige al 443",
     "certbot consigue y renueva el certificado SSL automaticamente",
     "Resultado: quien llega por HTTP acaba navegando por HTTPS",
     "80 -> 443 con certbot",
     "nginx sube a todo el mundo a https; certbot pone el certificado"),
  ]),
  ("LOS PROCESOS DENTRO DE LA MAQUINA", [
    ("pm2 mantiene el proceso vivo y lo reinicia si cae",
     "pm2 list muestra los procesos corriendo",
     "En la misma instancia conviven front (3000) y back (3001)",
     "Gestor de procesos",
     "pm2 es quien mantiene encendido el servidor dentro de la maquina"),
    ("Desde dentro de la instancia el servidor es solo localhost:3001",
     "curl localhost:3001/users devuelve la MISMA respuesta que el dominio publico",
     "El dominio, el firewall y nginx solo son el camino hasta ese localhost",
     "localhost:3001",
     "el servidor siempre vive en localhost; lo demas es la ruta para llegar"),
  ]),
  ("EL CAMINO COMPLETO", [
    ("navegador -> DNS -> IP publica -> firewall -> nginx -> localhost:3001",
     "Cada salto puede romper la peticion por su cuenta",
     "En local no hay saltos: vas directo a localhost:3000/users",
     "Los 5 saltos",
     "nombre, IP, puerto permitido, recepcionista y proceso: en ese orden"),
  ]),
  ("PARA QUE SIRVE EL BACKEND", [
    ("Das like: la app manda una peticion al servidor",
     "El servidor mira quien eres, guarda la accion y avisa al otro usuario",
     "Todo eso pasa entre tu clic y la notificacion del otro",
     "El ejemplo del like",
     "entre el clic y la notificacion siempre hay un servidor guardando y avisando"),
    ("Tu app esta personalizada segun tu perfil y a quien sigues",
     "Tu amigo solo recibe lo que va dirigido a el",
     "Pero alguien tiene que tener el estado de TODOS a la vez",
     "Servidor centralizado",
     "cada cliente ve su trozo; el servidor es el unico que ve todo el estado"),
    ("Traer datos, recibir datos y persistir datos",
     "Cualquier accion que toque datos pasa por ahi",
     "Si lo reduces a una palabra, el backend es eso",
     "El backend en una palabra: DATOS",
     "el backend existe para traer, recibir y persistir datos"),
  ]),
  ("COMO CARGA UN FRONTEND", [
    ("Lo primero que llega es el documento HTML",
     "Despues el navegador pide JS, CSS, fuentes e imagenes por separado",
     "Cada recurso es su propia peticion en la pestana Network",
     "Carga en cascada",
     "primero el HTML, luego un request por cada recurso que ese HTML pide"),
    ("Cuando llegan los CSS el navegador PINTA la pagina",
     "Cuando llega el JS se enganchan los event listeners (hidratacion)",
     "Por eso un boton puede verse bien y todavia no responder",
     "Pintado vs hidratacion",
     "el CSS lo hace verse; el JS lo hace responder"),
  ]),
  ("DONDE CORRE EL CODIGO", [
    ("El backend recibe la peticion, la procesa y manda el RESULTADO",
     "El frontend manda el CODIGO y el navegador lo ejecuta",
     "El runtime del frontend es el navegador del usuario",
     "El navegador es el runtime",
     "el back procesa y manda resultado; el front manda codigo y lo corre tu navegador"),
    ("El navegador ejecuta codigo que baja de un servidor desconocido",
     "Por eso lo corre aislado del sistema operativo, procesos y archivos",
     "Solo le deja el DOM, sus propias APIs (localStorage, cookies) y APIs externas permitidas",
     "Sandbox del navegador",
     "el navegador corre codigo ajeno, asi que lo encierra en una caja"),
  ]),
  ("POR QUE NO PONER EL BACKEND EN EL NAVEGADOR", [
    ("Un backend necesita escribir logs y leer variables de entorno",
     "Eso es tocar el sistema de archivos de la maquina",
     "El sandbox del navegador no lo permite, y con razon",
     "Razon 1: seguridad",
     "sin sistema de archivos ni variables de entorno no hay backend"),
    ("Un backend llama a APIs externas de muchos sitios distintos",
     "El navegador bloquea las llamadas a otro dominio salvo headers de CORS",
     "Y esas APIs externas no son tuyas: no controlas sus headers",
     "Razon 2: CORS",
     "no controlas los headers de una API ajena, asi que el navegador te la corta"),
    ("Los drivers nativos (pg, mongodb) usan sockets, binario y conexiones persistentes",
     "El servidor reutiliza una lista de conexiones: el connection pool",
     "Si cada usuario abriera la suya, la base de datos se ahogaria",
     "Razon 3: base de datos",
     "el servidor reutiliza un pool de conexiones; el navegador no puede sostener ninguna"),
    ("El frontend corre en movil, portatil o un equipo de 256 MB y un solo nucleo",
     "La logica pesada ahi se traba o se rompe",
     "A un servidor centralizado le subes CPU y RAM cuando quieras",
     "Razon 4: poder de computo",
     "no controlas el aparato del usuario; el servidor si lo escalas tu"),
  ]),
]
