# -*- coding: utf-8 -*-
NAME = "Backend"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Quiero que algo corra en un servidor y responda por la red", [
    ("Exponer una función para que se acceda por una URL",
     "Ruta / endpoint"),
    ("Distinguir pedir datos de enviar o crear datos",
     "Métodos HTTP (GET lee, POST crea, PUT/PATCH actualiza, DELETE borra)"),
    ("Comunicar cómo salió la operación",
     "Códigos de estado (200, 201, 400, 401, 404, 422, 500)"),
    ("Tener el framework para escribir la API en Python",
     "FastAPI + uvicorn (servidor ASGI)"),
  ]),
  ("Los datos que recibo pueden venir mal", [
    ("Garantizar que lo que entra tiene la forma correcta",
     "Validación con esquemas (Pydantic)"),
    ("Convertir entre objeto de Python y JSON",
     "Serialización / deserialización"),
    ("Responder 'tus datos están mal formados'",
     "Código 422 (Unprocessable Entity)"),
  ]),
  ("Los datos deben sobrevivir al reinicio", [
    ("Guardar información de forma permanente",
     "Base de datos"),
    ("Datos con esquema fijo y relaciones, con transacciones",
     "SQL (SQLite, PostgreSQL)"),
    ("Datos flexibles tipo documento, sin esquema rígido",
     "NoSQL"),
    ("Identificar cada fila de forma única e inequívoca",
     "Llave primaria"),
    ("Las cuatro operaciones básicas sobre los datos",
     "CRUD (Create, Read, Update, Delete)"),
    ("Hablar con la base de datos usando objetos de Python",
     "ORM (SQLAlchemy)"),
  ]),
  ("Tengo varios usuarios; debo saber quién es quién", [
    ("Verificar la identidad del usuario",
     "Autenticación (¿quién eres?)"),
    ("Verificar qué tiene permitido hacer",
     "Autorización (¿qué puedes?)"),
    ("Guardar contraseñas sin poder leerlas nunca",
     "Hashing (bcrypt) — one-way, NO encriptar"),
    ("Saber en cada petición quién es el usuario sin guardar sesión en el servidor",
     "Token / JWT"),
    ("Interceptar cada petición antes de que llegue a la ruta",
     "Middleware"),
  ]),
  ("Mis datos están relacionados (un usuario tiene muchos registros)", [
    ("Representar 'uno tiene muchos'",
     "Relación uno-a-muchos"),
    ("Que una tabla apunte a otra",
     "Llave foránea (apunta a la PK de otra tabla)"),
    ("Combinar dos tablas por una llave compartida",
     "Join"),
    ("Evitar repetir el mismo dato en muchos lados",
     "Normalización"),
  ]),
  ("¿Cómo lo pongo en internet sin que truene ni filtre secretos?", [
    ("Publicar la app para que el mundo la use",
     "Deployment (PaaS: Render/Railway)"),
    ("Mantener claves y secretos fuera del código",
     "Variables de entorno (.env)"),
    ("Ver qué falló en producción",
     "Logs"),
    ("Empaquetar la app con su entorno para que corra igual en todos lados",
     "Docker (contenedor)"),
  ]),
]

# INTEGRADOR: de las SENALES concretas al concepto + tip verbalizable.
ESTACIONES = [
  ("EL PUENTE HTTP", [
    ("No guarda memoria entre peticiones (stateless)",
     "Cada mensaje lleva método, ruta, headers y body",
     "Es la misma flecha que el fetch del frontend",
     "HTTP",
     "HTTP es petición→respuesta sin memoria: cada llamada empieza de cero"),
    ("GET solo lee y no cambia nada",
     "POST crea, PUT/PATCH actualiza, DELETE borra",
     "GET es idempotente y cacheable; POST no",
     "Métodos HTTP",
     "el método declara la intención: leer vs crear vs borrar"),
    ("2xx = salió bien",
     "4xx = culpa del cliente (404 no existe, 401 sin login, 422 datos mal)",
     "5xx = culpa del servidor",
     "Códigos de estado",
     "el primer dígito te dice de quién es la culpa"),
  ]),
  ("PERSISTENCIA", [
    ("Tabla con esquema fijo: filas y columnas",
     "Soporta relaciones y transacciones ACID",
     "Se consulta combinando tablas con joins",
     "Base de datos SQL / relacional",
     "SQL es para datos con forma fija y relaciones fuertes"),
    ("Es la columna que identifica única e inequívocamente cada fila",
     "Nunca se repite, nunca es nula",
     "Otras tablas la referencian",
     "Llave primaria (PK)",
     "la PK es el DNI de la fila"),
    ("Traduce filas de la tabla a objetos de Python y viceversa",
     "Te evita escribir SQL a mano",
     "SQLAlchemy es el más común en Python",
     "ORM",
     "el ORM es el traductor entre tablas y objetos"),
    ("Es una columna que apunta a la llave primaria de otra tabla",
     "Así se enlaza 'el pedido pertenece a este usuario'",
     "Hace posible el join",
     "Llave foránea (FK)",
     "la FK es el puntero de una tabla hacia otra"),
  ]),
  ("IDENTIDAD Y SEGURIDAD", [
    ("Transforma la contraseña en algo irreversible",
     "No se puede deshacer (one-way)",
     "Lleva salt para que dos contraseñas iguales no se vean iguales",
     "Hashing",
     "encriptar es reversible; hashear no: por eso la contraseña se hashea"),
    ("Una pregunta verifica identidad, la otra verifica permisos",
     "Login vs '¿puedes borrar esto?'",
     "Primero autenticas, luego autorizas",
     "Autenticación vs Autorización",
     "autenticar = quién eres; autorizar = qué puedes hacer"),
    ("Es una credencial firmada que el cliente guarda y reenvía",
     "El servidor la verifica sin guardar ninguna sesión",
     "Viaja en cada petición dentro del header",
     "Token / JWT",
     "el JWT es un pase firmado: el servidor lo valida sin recordar nada"),
  ]),
]
