# -*- coding: utf-8 -*-
NAME = "Analisis de Datos"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Tengo datos en un archivo y quiero cargarlos y mirarlos", [
    ("Trabajar una tabla 2D con filas y columnas etiquetadas",
     "DataFrame (pandas)"),
    ("Trabajar una sola columna",
     "Series"),
    ("Cargar un archivo de datos",
     "read_csv / read_excel"),
    ("Echar un primer vistazo a forma, tipos y resumen",
     "head(), info(), describe(), shape, dtypes"),
    ("Tener un entorno para explorar paso a paso",
     "Jupyter / notebooks"),
  ]),
  ("Los datos están sucios", [
    ("Manejar celdas vacías o ausentes",
     "NaN + dropna (borrar) vs fillna (imputar)"),
    ("Detectar y quitar filas repetidas",
     "duplicated() / drop_duplicates()"),
    ("Arreglar una columna que es texto pero debería ser número o fecha",
     "Conversión de tipos (astype, to_numeric, to_datetime)"),
    ("Limpiar texto inconsistente (espacios, mayúsculas)",
     "Métodos de texto (.str.strip, .str.lower)"),
  ]),
  ("Quiero responder preguntas: filtrar, agrupar, resumir", [
    ("Seleccionar filas y columnas por etiqueta o por posición",
     "loc (etiqueta) / iloc (posición)"),
    ("Quedarme solo con las filas que cumplen una condición",
     "Filtrado booleano (definir una cohorte)"),
    ("Resumir por grupos (promedio por categoría)",
     "groupby (split-apply-combine)"),
    ("Calcular resúmenes de cada grupo",
     "Agregaciones (mean, sum, count, median)"),
  ]),
  ("Necesito hacer cuentas rápidas sobre muchos números", [
    ("Guardar muchos números del mismo tipo de forma eficiente",
     "numpy array"),
    ("Operar sobre toda la columna de golpe, sin bucles",
     "Vectorización"),
    ("Entender por qué es más rápido que una lista de Python",
     "Memoria contigua + operación en C (no Python puro)"),
  ]),
  ("Quiero VER los datos, no solo números", [
    ("Entender el lienzo y los sub-gráficos",
     "matplotlib (Figure vs Axes)"),
    ("Hacer gráficas estadísticas bonitas en una línea",
     "seaborn"),
    ("Elegir la gráfica correcta para mi pregunta",
     "distribución (histograma), comparación (barras), relación (scatter), tendencia (línea)"),
  ]),
  ("Quiero sacar conclusiones estadísticas (mi meta-análisis)", [
    ("Distinguir describir la muestra de generalizar a la población",
     "Estadística descriptiva vs inferencial"),
    ("Expresar el rango plausible del valor real",
     "Intervalo de confianza (IC)"),
    ("Medir cuán grande es el efecto, no solo si existe",
     "Tamaño de efecto"),
    ("Combinar varios estudios ponderando por su peso",
     "Pooling ponderado (meta-análisis)"),
    ("Medir cuánto discrepan los estudios entre sí",
     "Heterogeneidad (Q, I²)"),
    ("Decidir si asumo un único efecto o una distribución de efectos",
     "Efectos fijos vs aleatorios"),
  ]),
  ("Que todo sea reproducible y reusable", [
    ("Empaquetar lógica para reusarla",
     "Funciones"),
    ("Que el azar dé el mismo resultado cada vez",
     "Semilla (seed)"),
    ("Pasar de exploración desordenada a un producto",
     "notebook → script / pipeline"),
  ]),
]

# INTEGRADOR: de las SENALES concretas al concepto + tip verbalizable.
ESTACIONES = [
  ("CARGA Y EXPLORACIÓN", [
    ("Tabla 2D con índice de filas y columnas etiquetadas",
     "Es la estructura central de pandas",
     "Como una hoja de cálculo, pero en código",
     "DataFrame",
     "el DataFrame es la hoja de Excel de Python"),
    ("Es una sola columna del DataFrame",
     "Un array 1D con etiquetas (índice)",
     "Cada columna del DataFrame es una de estas",
     "Series",
     "una Series es una columna; muchas Series forman un DataFrame"),
    ("De un vistazo da filas, columnas, tipos y conteo de no-nulos",
     "Es el primer diagnóstico de los datos",
     "Revela qué columnas tienen faltantes",
     "info()",
     "info() son los signos vitales del dataset"),
  ]),
  ("LIMPIEZA", [
    ("Es la marca de un dato ausente",
     "No es cero ni cadena vacía: es 'no hay dato'",
     "Se propaga y contamina los cálculos",
     "NaN",
     "NaN es 'falta el dato', distinto de 0"),
    ("Una opción borra la fila incompleta",
     "La otra rellena el hueco con media/mediana/0",
     "La decisión depende de cuántos faltan y por qué",
     "dropna vs fillna",
     "borro si son pocos y aleatorios; imputo si perder la fila cuesta caro"),
    ("La columna trae números pero pandas la ve como texto",
     "No puedes sumar ni promediar",
     "Hay que convertir el tipo",
     "Conversión de tipos",
     "un número atrapado como texto: lo libero con to_numeric"),
  ]),
  ("TRANSFORMACIÓN", [
    ("Parto la tabla en grupos según una columna",
     "Aplico una función a cada grupo (media, conteo)",
     "Recombino los resultados en un resumen",
     "groupby",
     "groupby es partir-aplicar-combinar: es el GROUP BY de SQL"),
    ("Opero toda la columna de una sola vez",
     "Sin escribir un bucle for",
     "Es más rápido y más legible",
     "Vectorización",
     "dejar de pensar 'uno por uno' y pensar 'todo de golpe'"),
    ("Combino dos tablas por una llave compartida",
     "Funciona igual que un join de SQL",
     "Enlazo, por ejemplo, pacientes con sus resultados",
     "merge",
     "el merge de pandas es el join de SQL: el mismo pensamiento relacional"),
  ]),
  ("INFERENCIA", [
    ("Una describe lo que tengo, la otra concluye sobre lo que no vi",
     "Media y desviación vs prueba de hipótesis",
     "Resumir la muestra vs generalizar a la población",
     "Descriptiva vs Inferencial",
     "describir es contar lo que veo; inferir es apostar sobre lo que no veo"),
    ("Es el rango plausible donde está el valor real",
     "Más estrecho significa más preciso",
     "Si cruza el valor nulo, no es significativo",
     "Intervalo de confianza",
     "el IC es el margen de error honesto de tu estimación"),
    ("Mide cuánto discrepan los estudios entre sí",
     "Un I² alto significa que los estudios no concuerdan",
     "Decide entre efectos fijos y aleatorios",
     "Heterogeneidad (I²)",
     "I² alto: los estudios cuentan historias distintas, usa efectos aleatorios"),
  ]),
]
