# -*- coding: utf-8 -*-
NAME = "Diagramas"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto/herramienta que nace.
EJES = [
  ("Tengo un árbol de decisión en la cabeza y quiero verlo dibujado en una página", [
    ("Convertir texto en un diagrama de nodos y flechas sin dibujar a mano",
     "Mermaid (graph TD; A --&gt; B)"),
    ("Escribir el árbol como lista con viñetas y que se vuelva mapa mental colapsable",
     "Markmap (outline → mindmap)"),
    ("Tener una página donde mostrarlo",
     "HTML mínimo (un archivo .html que abres en el navegador)"),
    ("Dibujarlo sin instalar nada, directo en mi repo",
     "Bloque ```mermaid en un archivo .md (GitHub lo renderiza solo)"),
  ]),
  ("Quiero controlar cómo se ve y se ramifica el árbol", [
    ("La pieza que representa un concepto, paso o decisión",
     "Nodo"),
    ("La flecha que conecta dos pasos y dice su relación",
     "Arista / edge (A --&gt; B)"),
    ("Etiquetar una rama, p. ej. «sí» / «no»",
     "Etiqueta en la arista (A --&gt;|sí| B)"),
    ("Indicar la dirección del árbol: de arriba-abajo o de lado",
     "graph TD (top-down) / graph LR (left-right)"),
    ("Distinguir un nodo de decisión de uno de acción",
     "Formas de nodo: [rect]=paso, {rombo}=decisión, (redondeado)=inicio/fin"),
  ]),
  ("Quiero acceder al árbol de distintas formas, no solo mirarlo", [
    ("Que al hacer clic en un nodo me lleve a más info u otra página",
     "Click interactivo (Mermaid: click NODO; o JS)"),
    ("Colapsar y expandir ramas para no saturar la vista",
     "Markmap colapsable / &lt;details&gt;&lt;summary&gt; en HTML"),
    ("Ejecutar algo justo cuando hago clic",
     "Event listener (addEventListener('click', fn))"),
    ("Buscar o resaltar un nodo por su texto",
     "JavaScript (filtrar/resaltar el DOM)"),
  ]),
  ("Ya funciona en mi compu; quiero que sea una página web de verdad con link", [
    ("Publicar el archivo del repo como sitio con URL pública",
     "GitHub Pages"),
    ("Que el sitio se actualice solo cuando subo cambios",
     "push a la rama → Pages redeploya"),
    ("Que se vea bien en el celular en la clínica",
     "Responsive (meta viewport + unidades relativas)"),
  ]),
]

# INTEGRADOR: de las SENALES concretas al concepto + tip verbalizable ("Dilo asi").
ESTACIONES = [
  ("LA HERRAMIENTA QUE DIBUJA", [
    ("Conviertes texto en un diagrama de nodos y flechas",
     "Escribes algo como 'graph TD; A --&gt; B'",
     "GitHub y muchos editores lo renderizan sin instalar nada",
     "Mermaid",
     "Mermaid es texto que se vuelve diagrama: tú describes el árbol, él lo dibuja"),
    ("Partes de una lista con viñetas indentada",
     "La vuelve un mapa mental con ramas que se abren y cierran",
     "Ideal para jerarquías tipo «todo sobre la diabetes»",
     "Markmap",
     "Markmap es tu outline convertido en árbol colapsable"),
  ]),
  ("LA GRAMÁTICA DEL ÁRBOL", [
    ("Es cada caja del diagrama",
     "Representa un concepto, un paso o una decisión",
     "Lleva un id y una forma",
     "Nodo",
     "el nodo es el QUÉ: un paso o una decisión del árbol"),
    ("Es la flecha entre dos nodos",
     "Dice la relación o el flujo entre pasos",
     "Se escribe A --&gt; B, con etiqueta A --&gt;|sí| B",
     "Arista (edge)",
     "la arista es el CÓMO se conecta: el camino entre pasos"),
    ("Cambia hacia dónde crece el diagrama",
     "TD lo baja de arriba-abajo; LR lo extiende de lado",
     "Se pone al inicio: graph TD o graph LR",
     "Dirección del grafo",
     "TD baja, LR va de lado: eliges según quepa mejor"),
    ("La forma de la caja indica el tipo de paso",
     "Rombo = decisión, rectángulo = acción, redondeado = inicio/fin",
     "Mismo nodo, distinto significado visual",
     "Forma de nodo",
     "la forma dice el tipo: el rombo es un «¿sí o no?»"),
  ]),
  ("ACCESO E INTERACCIÓN", [
    ("Haces clic en un nodo y pasa algo",
     "Te lleva a una URL o a otra vista",
     "En Mermaid: click NODO con una liga",
     "Click interactivo",
     "un nodo deja de ser dibujo y se vuelve puerta"),
    ("Una rama se abre y se cierra a voluntad",
     "Evita mostrar el árbol entero de golpe",
     "Markmap lo hace nativo; en HTML, &lt;details&gt;",
     "Colapsar / expandir",
     "muestro solo la rama que me importa, el resto plegado"),
    ("Una función queda a la espera de un evento",
     "Se dispara con un clic, una tecla o un scroll",
     "Se registra con addEventListener('click', fn)",
     "Event listener",
     "registro la función y el navegador la llama al hacer clic"),
  ]),
  ("PUBLICAR", [
    ("Tomas un archivo HTML o .md de tu repo",
     "Lo sirve como sitio con URL pública",
     "Se actualiza cuando haces push",
     "GitHub Pages",
     "Pages convierte tu repo en web: de archivo local a link que abres en el cel"),
    ("Pones un bloque de código mermaid en un .md",
     "GitHub lo dibuja sin instalar ni configurar nada",
     "Es el camino de menor fricción para empezar",
     "Mermaid en Markdown",
     "el mínimo viable: ni HTML, solo markdown y GitHub lo pinta"),
  ]),
]
