# -*- coding: utf-8 -*-
# Contenido derivado del tutorial "FastAPI - real project" (Tech With Tim,
# youtube.com/watch?v=SR5NYCdzKkc): app de fotos/videos con auth, BD e ImageKit.
# Misma metodologia de ejes que frontend/backend/data/flask/python/pandas.
NAME = "FastAPI"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Quiero entender la estructura de una URL y de las peticiones", [
    ("La parte que identifica el sitio (acaba en .com/.dev)",
     "dominio"),
    ("La ruta concreta a un recurso",
     "path / endpoint"),
    ("Datos extra para filtrar, tras un ?",
     "query parameter (varios separados por &amp;)"),
    ("Lo que el usuario ve y con lo que interactua",
     "cliente / frontend"),
    ("La capa segura que controla los datos en un servidor",
     "API / backend"),
    ("Lo que el frontend manda al backend",
     "request (metodo, path, body, headers)"),
    ("Lo que el backend devuelve",
     "response (status code, body, headers)"),
  ]),
  ("Quiero declarar que operacion hace cada endpoint", [
    ("Leer / obtener datos",
     "GET"),
    ("Crear datos",
     "POST"),
    ("Actualizar datos",
     "PUT / PATCH"),
    ("Borrar datos",
     "DELETE"),
    ("Comunicar como salio (exito / no existe / sin permiso)",
     "status codes (200, 201, 404, 401, 403, 422, 500)"),
  ]),
  ("Quiero arrancar una API con FastAPI", [
    ("Crear la aplicacion",
     "from fastapi import FastAPI; app = FastAPI()"),
    ("Definir un endpoint",
     "decorador @app.get('/ruta') sobre una funcion"),
    ("Devolver datos",
     "un dict (se vuelve JSON) o un modelo Pydantic"),
    ("Servir la app con un servidor ASGI",
     "uvicorn (uvicorn.run con reload=True en desarrollo)"),
    ("Documentar y probar la API sin escribir nada",
     "/docs (Swagger) y /redoc"),
  ]),
  ("Quiero recibir datos del cliente de distintas formas", [
    ("Una parte dinamica de la ruta (un id)",
     "path parameter: @app.get('/post/{id}'), id: int"),
    ("Un dato opcional de filtrado tras el ?",
     "query parameter: limit: int = None"),
    ("Datos en el cuerpo de la peticion",
     "request body con un esquema Pydantic (class X(BaseModel))"),
    ("Un archivo subido",
     "file: UploadFile = File(...)"),
    ("Campos de un formulario",
     "caption: str = Form(...)"),
  ]),
  ("Quiero que FastAPI valide los datos por mi", [
    ("Validar tipos de entrada y salida automaticamente",
     "type hints en los parametros"),
    ("Definir la forma del cuerpo que acepto",
     "esquema Pydantic (hereda de BaseModel)"),
    ("Declarar y validar lo que devuelvo",
     "response model: -&gt; PostResponse"),
    ("Devolver un error con su codigo",
     "raise HTTPException(status_code=404, detail='...')"),
  ]),
  ("Quiero que los datos sobrevivan al reinicio", [
    ("Hablar con la BD con objetos de Python (sin SQL crudo)",
     "ORM (SQLAlchemy)"),
    ("Definir una tabla como clase",
     "class Post(Base): __tablename__, Column(...)"),
    ("Dar a cada fila un id unico automatico",
     "UUID primary_key, default=uuid4"),
    ("Conectar a una BD local asincrona",
     "DATABASE_URL 'sqlite+aiosqlite:///./test.db'"),
    ("Crear las tablas al arrancar la app",
     "create_all dentro de un lifespan (@asynccontextmanager)"),
  ]),
  ("Quiero usar la base de datos dentro de mis endpoints", [
    ("Conseguir una sesion de BD automaticamente",
     "session = Depends(get_async_session) (inyeccion de dependencias)"),
    ("Guardar un objeto nuevo",
     "session.add(obj) + await session.commit()"),
    ("Rellenar los campos autogenerados (id, created_at)",
     "await session.refresh(obj)"),
    ("Consultar registros",
     "await session.execute(select(Post).order_by(...))"),
    ("Sacar un unico resultado",
     "result.scalars().first()"),
  ]),
  ("Quiero subir y servir imagenes/videos sin dolor", [
    ("Delegar el almacenamiento y la entrega de media",
     "ImageKit (servicio externo)"),
    ("Subir el archivo desde el backend (no desde el front)",
     "imagekit.upload_file(...)"),
    ("Transformar la imagen/video (tamano, recorte, calidad, texto)",
     "parametros EN LA URL (tr:w-300,...)"),
    ("Guardar claves y secretos fuera del codigo",
     "variables de entorno en .env (python-dotenv, os.getenv)"),
  ]),
  ("Quiero login y saber quien es cada usuario", [
    ("Identificar al usuario en cada peticion",
     "JWT (Json Web Token)"),
    ("Conseguir el token",
     "iniciar sesion en /auth/jwt/login con credenciales"),
    ("Mandar el token en cada peticion",
     "en el header: Authorization: Bearer &lt;token&gt;"),
    ("Manejar registro/login/usuarios sin escribirlo",
     "fastapi-users (routers ya incluidos)"),
    ("Firmar los tokens de forma unica para esta app",
     "un SECRET (no compartir)"),
  ]),
  ("Quiero relacionar usuarios con sus posts y proteger rutas", [
    ("Modelar 'un usuario tiene muchos posts'",
     "relacion uno-a-muchos: relationship + ForeignKey + back_populates"),
    ("Que el post apunte a su dueno",
     "ForeignKey('user.id') en el post"),
    ("Exigir estar logueado para usar un endpoint",
     "user = Depends(current_active_user)"),
    ("Que solo el dueno borre su post",
     "if post.user_id != user.id: raise HTTPException(403)"),
  ]),
]

# INTEGRADOR: de las SENALES concretas (discriminadores) al concepto + tip verbalizable.
ESTACIONES = [
  ("ANATOMIA DE LA URL Y LA PETICION", [
    ("El dominio es el sitio (acaba en .com/.dev)",
     "El path/endpoint es la ruta al recurso (/post/123)",
     "El query parameter va tras el ? y filtra (?limit=3); varios con &amp;",
     "Partes de la URL",
     "dominio = sitio, path = ruta, query = filtro tras ?"),
    ("El request lo manda el frontend: metodo, path, body y headers",
     "El response vuelve del backend: status code, body y headers",
     "El body lleva datos; los headers, info como la autenticacion",
     "Request vs response",
     "request va del cliente; response vuelve del servidor"),
    ("El cliente/frontend es lo que el usuario ve y toca",
     "La API/backend es la capa segura que controla los datos",
     "En toda operacion con datos: el front pide, el back responde",
     "Frontend vs backend (API)",
     "el front pide; el back (API) controla los datos de forma segura"),
  ]),
  ("METODOS Y CODIGOS", [
    ("GET lee; POST crea; PUT/PATCH actualiza; DELETE borra",
     "El metodo declara la INTENCION de la peticion",
     "El mismo path puede responder a varios metodos distintos",
     "Metodos HTTP",
     "GET lee, POST crea, PUT/PATCH actualiza, DELETE borra"),
    ("2xx = salio bien (200 ok, 201 creado)",
     "4xx = culpa del cliente (404 no existe, 401 sin login, 403 sin permiso, 422 datos mal)",
     "5xx = culpa del servidor (500)",
     "Status codes",
     "el primer digito dice de quien es la culpa: 2 ok, 4 cliente, 5 servidor"),
  ]),
  ("ARRANCAR FASTAPI", [
    ("app = FastAPI() crea la aplicacion",
     "@app.get('/ruta') sobre una funcion define un endpoint",
     "Lo que la funcion retorna (un dict) se manda como JSON",
     "App y endpoint",
     "FastAPI() crea la app; el decorador @app.get define la ruta"),
    ("uvicorn es el servidor ASGI que sirve la app (reload=True en dev)",
     "/docs (Swagger) documenta Y deja probar la API sola",
     "/redoc es otra vista de esa misma documentacion",
     "uvicorn y /docs",
     "uvicorn la sirve; /docs la documenta y la prueba sola"),
  ]),
  ("RECIBIR DATOS", [
    ("Path parameter: parte dinamica de la ruta /post/{id}, va entre {}",
     "Query parameter: opcional tras el ?, p.ej. limit: int = None",
     "Request body: datos en el cuerpo, via un esquema Pydantic",
     "Vias de entrada",
     "path = en la ruta, query = tras ?, body = en el cuerpo (Pydantic)"),
    ("file: UploadFile = File(...) recibe un archivo subido",
     "caption: str = Form(...) recibe un campo de formulario",
     "Son tipos de entrada distintos a query y body",
     "File / Form",
     "File recibe archivos; Form recibe campos de formulario"),
  ]),
  ("VALIDACION Y ERRORES", [
    ("Un esquema Pydantic (class X(BaseModel)) define la forma del body",
     "Los type hints validan automaticamente entrada y salida",
     "Si el tipo no encaja, FastAPI lanza el error solo (422)",
     "Validacion automatica",
     "Pydantic + type hints validan los datos por ti"),
    ("-&gt; PostResponse declara y valida lo que se DEVUELVE",
     "Mejora la documentacion y bloquea devolver algo que no encaje",
     "raise HTTPException(codigo, detail) devuelve un error con su codigo",
     "Salida y errores",
     "-&gt; Modelo valida la salida; HTTPException devuelve el error"),
  ]),
  ("BASE DE DATOS (ORM ASINCRONO)", [
    ("El ORM (SQLAlchemy) deja usar objetos de Python en vez de SQL crudo",
     "Una clase que hereda de Base = una tabla (con __tablename__)",
     "UUID primary_key default=uuid4 genera un id unico automatico",
     "Modelo SQLAlchemy",
     "clase que hereda de Base = tabla; el UUID primary_key se autogenera"),
    ("session.add(obj) encola el objeto para guardarlo",
     "await session.commit() lo escribe de verdad en la BD",
     "await session.refresh(obj) rellena el id y created_at autogenerados",
     "Guardar en BD",
     "add encola, commit escribe, refresh trae los campos autogenerados"),
    ("Depends(get_async_session) inyecta la sesion de BD en el endpoint",
     "Es inyeccion de dependencias: FastAPI corre esa funcion y te pasa el resultado",
     "Consultas: session.execute(select(Post)...); scalars().first() da uno solo",
     "Inyeccion de dependencias",
     "Depends ejecuta una funcion y te inyecta su resultado (la sesion de BD)"),
  ]),
  ("MEDIA Y SECRETOS", [
    ("ImageKit aloja y entrega las imagenes/videos (no los guardas tu)",
     "imagekit.upload_file(...) sube desde el backend (mas seguro que desde el front)",
     "Transformas tamano/recorte/calidad/texto con parametros EN LA URL",
     "ImageKit",
     "ImageKit guarda y entrega la media; la transformas por la URL"),
    ("Las claves y secretos van en un archivo .env, fuera del codigo",
     "python-dotenv las carga; os.getenv las lee",
     "Nunca se suben al repo ni se comparten",
     "Variables de entorno",
     ".env guarda los secretos; os.getenv los lee"),
  ]),
  ("AUTENTICACION JWT", [
    ("Al iniciar sesion, el backend devuelve un JWT (token firmado)",
     "El cliente lo guarda y lo manda en cada peticion (header Authorization: Bearer ...)",
     "Quien tenga ese token ES ese usuario a ojos de la API",
     "JWT",
     "login da un token firmado; lo mandas en cada request y te identifica"),
    ("fastapi-users genera los routers de registro/login/usuarios",
     "El SECRET firma los tokens; si se filtra, se pueden falsificar",
     "current_active_user da el usuario validando su token",
     "fastapi-users",
     "fastapi-users trae el login hecho; el SECRET firma los tokens"),
  ]),
  ("RELACIONES Y PROTECCION", [
    ("ForeignKey('user.id') en el post apunta a su dueno",
     "relationship + back_populates enlaza post y user en ambos lados",
     "Modela 'un usuario tiene muchos posts'",
     "Relacion uno-a-muchos",
     "la FK apunta al dueno; relationship enlaza ambos lados"),
    ("Depends(current_active_user) exige estar logueado para entrar al endpoint",
     "autenticar (quien eres) NO es lo mismo que autorizar (que puedes hacer)",
     "if post.user_id != user.id: raise HTTPException(403) = solo el dueno borra",
     "Proteger y autorizar",
     "current_active_user autentica; el check de user_id autoriza"),
  ]),
]
