# -*- coding: utf-8 -*-
# Contenido derivado del tutorial "Python Website Full Tutorial - Flask,
# Authentication, Databases & More" (Tech With Tim, youtu.be/dam0GPOAvVI).
# Verificado contra la transcripcion completa del video.
# Misma metodologia de ejes que frontend/backend/data.
NAME = "Flask"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Quiero que Python responda en el navegador cuando entro a una direccion", [
    ("Tener el micro-framework de Python para servir paginas web",
     "Flask"),
    ("Crear la instancia de la aplicacion",
     "app = Flask(__name__)"),
    ("Asociar una URL a la funcion que la maneja",
     "Ruta / view (decorador @app.route)"),
    ("Lo que la funcion retorna sea lo que ve el navegador",
     "El return de la vista = la respuesta HTTP"),
    ("Recargar solo al guardar y ver el traceback mientras desarrollo",
     "app.run(debug=True) (modo debug, NUNCA en produccion)"),
  ]),
  ("Mi app crece y no quiero todo amontonado en un solo archivo", [
    ("Construir y configurar la app dentro de una funcion para testearla y evitar imports circulares",
     "App factory: create_app() en __init__.py"),
    ("Partir las rutas en modulos por tema (vistas, auth)",
     "Blueprint"),
    ("Enchufar cada grupo de rutas a la app",
     "app.register_blueprint(bp, url_prefix='/')"),
  ]),
  ("No quiero escribir HTML pegado en Python ni repetir el header en cada pagina", [
    ("Devolver un archivo HTML desde una ruta",
     "render_template('pagina.html')"),
    ("Meter variables y logica de Python dentro del HTML",
     "Jinja: {{ }} imprime, {% %} decide"),
    ("Pasar datos de Python a la plantilla",
     "render_template('p.html', user=current_user)"),
    ("Tener un esqueleto comun (nav, head) que las demas paginas reutilizan",
     "Herencia de plantillas: base.html + {% block %}"),
    ("Generar la URL de una ruta por su NOMBRE, no escribiendola a mano",
     "url_for('views.home')"),
  ]),
  ("Necesito recibir lo que el usuario escribe en un formulario", [
    ("Permitir que una ruta acepte envios ademas de lecturas",
     "methods=['GET', 'POST'] en @app.route"),
    ("Saber si la peticion fue de leer o de enviar",
     "if request.method == 'POST'"),
    ("Leer los campos que mando el formulario (por su atributo name)",
     "request.form.get('campo')"),
    ("Mandar al usuario a otra ruta despues de procesar el envio",
     "redirect(url_for('views.home')) (patron POST-redirect-GET)"),
  ]),
  ("Quiero avisar 'cuenta creada' o 'contrasena incorrecta' y que se vea una sola vez", [
    ("Mandar un mensaje temporal a la siguiente pagina",
     "flash('texto')"),
    ("Clasificar el aviso como exito o error (para el color)",
     "flash(msg, category='error')"),
    ("Mostrar esos mensajes desde la plantilla (en base.html)",
     "get_flashed_messages(with_categories=True)"),
  ]),
  ("Los usuarios y sus datos deben sobrevivir al reinicio del servidor", [
    ("Hablar con la base de datos con objetos de Python, sin SQL a mano",
     "Flask-SQLAlchemy (ORM): db = SQLAlchemy(), db.init_app(app)"),
    ("Definir una tabla como una clase",
     "class User(db.Model) + db.Column(...)"),
    ("Que cada fila tenga un identificador unico automatico",
     "id = db.Column(db.Integer, primary_key=True)"),
    ("Prohibir dos usuarios con el mismo email",
     "db.Column(db.String(150), unique=True)"),
    ("Que la fecha de creacion se rellene sola",
     "default=func.now() en una columna db.DateTime"),
    ("Modelar 'un usuario tiene muchas notas'",
     "db.relationship (lado uno) + db.ForeignKey (lado muchos)"),
    ("Crear el archivo .db y las tablas la primera vez",
     "db.create_all() (guardado con os.path.exists para no recrearlo)"),
  ]),
  ("Necesito buscar, guardar y borrar registros en la base", [
    ("Buscar registros por el valor de una columna",
     "Model.query.filter_by(email=...).first()"),
    ("Buscar un registro directo por su llave primaria",
     "Model.query.get(id)"),
    ("Guardar un objeto nuevo",
     "db.session.add(obj) + db.session.commit()"),
    ("Borrar un objeto",
     "db.session.delete(obj) + db.session.commit()"),
  ]),
  ("Las contrasenas no pueden guardarse legibles y quiero recordar quien inicio sesion", [
    ("Guardar la contrasena de forma irreversible",
     "generate_password_hash(pw, method='sha256') (Werkzeug)"),
    ("Verificar el login sin descifrar nada",
     "check_password_hash(user.password, intento)"),
    ("Recordar al usuario logueado entre peticiones",
     "Flask-Login: login_user(user, remember=True) / logout_user()"),
    ("Bloquear rutas para quien no inicio sesion",
     "@login_required"),
    ("Saber en cualquier vista o plantilla quien es el usuario actual",
     "current_user"),
    ("Ensenarle a Flask-Login a recuperar al usuario por su id en cada peticion",
     "@login_manager.user_loader"),
    ("Firmar la cookie de sesion para que no se falsifique",
     "app.config['SECRET_KEY']"),
  ]),
]

# INTEGRADOR: de las SENALES concretas (discriminadores) al concepto + tip verbalizable.
ESTACIONES = [
  ("ARRANCAR FLASK", [
    ("app = Flask(__name__) crea la aplicacion",
     "El __name__ le dice a Flask donde estan las carpetas templates/ y static/",
     "Se suele construir dentro de create_app() y retornar la app",
     "Instancia Flask",
     "Flask(__name__) crea la app; __name__ ancla donde buscar archivos"),
    ("Es un decorador que va ENCIMA de la funcion que responde a una URL",
     "El argumento es el PATH ('/', '/login'), no el nombre de la funcion",
     "Lo que la funcion retorna se manda tal cual al navegador",
     "Ruta / @app.route",
     "la ruta mapea una URL a una funcion; su return es la respuesta"),
    ("Recarga el servidor solo al guardar y muestra el traceback en el navegador",
     "Es exclusivo de desarrollo: JAMAS se deja activo en produccion",
     "Se activa con app.run(debug=True)",
     "Modo debug",
     "debug=True = autoreload + traceback, solo mientras desarrollas"),
  ]),
  ("ESTRUCTURA DE LA APP", [
    ("Es una funcion que construye, configura y RETORNA la app",
     "Permite varias instancias (test/prod) y evita imports circulares",
     "Dentro registras la DB, los blueprints y la config",
     "App factory (create_app)",
     "create_app arma la app dentro de una funcion en vez de a nivel global"),
    ("Agrupa rutas relacionadas en un modulo aparte (auth, views)",
     "Se define con Blueprint('nombre', __name__)",
     "No hace NADA hasta que register_blueprint lo conecta a la app",
     "Blueprint",
     "el blueprint es un paquete de rutas que luego enchufas a la app"),
  ]),
  ("PLANTILLAS (JINJA)", [
    ("{{ x }} imprime un valor; {% if %}/{% for %} mete logica",
     "Los datos llegan como argumentos extra de render_template",
     "El archivo vive en la carpeta templates/",
     "Jinja",
     "doble llave muestra, llave-porcentaje decide"),
    ("{% extends 'base.html' %} hereda el esqueleto comun",
     "{% block content %} es el hueco que cada pagina rellena",
     "Evita repetir nav y head en cada archivo",
     "Herencia de plantillas",
     "base.html es el molde; los blocks son los huecos que rellenas"),
    ("Construye la URL a partir del NOMBRE de la vista, no del path escrito",
     "Si cambias la ruta, los enlaces no se rompen",
     "Sirve para rutas (url_for('views.home')) y para estaticos (url_for('static', filename=...))",
     "url_for",
     "url_for nombra la ruta en vez de escribir la URL a mano"),
  ]),
  ("FORMULARIOS / PETICION", [
    ("Por defecto una ruta solo acepta GET",
     "Para recibir un formulario hay que declarar methods=['GET', 'POST']",
     "GET trae el formulario vacio, POST procesa el envio",
     "methods en la ruta",
     "sin methods=['POST'] la ruta da 'method not allowed' al enviar"),
    ("request.form.get('campo') lee lo que el usuario escribio (por su name)",
     "request.method dice si fue GET o POST",
     "Solo trae datos del formulario en un POST",
     "objeto request",
     "request es el sobre con todo lo que mando el cliente"),
    ("Tras procesar el POST manda al usuario a OTRA ruta",
     "Evita que reenvie el formulario al recargar (POST-redirect-GET)",
     "Casi siempre se combina con url_for",
     "redirect",
     "redirect cierra el POST mandando a una GET limpia"),
  ]),
  ("MENSAJES Y SEGURIDAD", [
    ("Guarda un mensaje que se muestra UNA sola vez en la siguiente peticion",
     "Lleva una categoria ('success'/'error') para decidir el color",
     "Se lee en la plantilla con get_flashed_messages(with_categories=True)",
     "flash",
     "flash deja una nota de un solo uso para la proxima pagina"),
    ("generate_password_hash convierte la contrasena en algo IRREVERSIBLE (one-way)",
     "check_password_hash compara el intento contra el hash, sin descifrar",
     "Jamas se guarda ni se compara el texto plano",
     "Hashing de contrasena (Werkzeug)",
     "encriptar es reversible; hashear no: por eso la contrasena se hashea"),
    ("Firma la cookie de sesion para que el cliente no pueda falsificarla",
     "Sin ella ni la sesion ni los flash funcionan",
     "Debe ser secreta y estable (en produccion, fuera del codigo)",
     "SECRET_KEY",
     "la SECRET_KEY firma la sesion; sin ella no hay login ni flash"),
  ]),
  ("BASE DE DATOS (ORM)", [
    ("Una clase que hereda de db.Model equivale a UNA tabla",
     "Cada db.Column es una columna con su tipo (db.Integer, db.String(150)...)",
     "primary_key=True marca el id; unique=True prohibe repetidos (p.ej. email)",
     "Modelo de Flask-SQLAlchemy",
     "la clase es la tabla y cada atributo Column es una columna"),
    ("db.ForeignKey('user.id') usa el nombre de la TABLA en minuscula",
     "db.relationship('Note') usa el nombre de la CLASE en mayuscula",
     "La FK va en el lado 'muchos' (la nota); el relationship en el 'uno' (el usuario)",
     "Relacion uno-a-muchos",
     "FK = tabla.minuscula apunta abajo; relationship = Clase.mayuscula colecciona arriba"),
    ("Crea el archivo .db y las tablas a partir de los modelos",
     "Se guarda con os.path.exists para NO recrearla si ya existe",
     "No migra ni actualiza tablas que ya existen",
     "db.create_all()",
     "create_all crea las tablas desde los modelos, una sola vez"),
  ]),
  ("CONSULTAR Y GUARDAR (ORM)", [
    ("filter_by(campo=valor) busca por CUALQUIER columna",
     "Devuelve un query; necesitas .first() para el primer resultado (o None)",
     "get(id) en cambio busca DIRECTO por la primary key",
     "Consulta del ORM",
     "filter_by(...).first() busca por columna; get() va directo por la PK"),
    ("db.session.add(obj) encola el objeto para guardarlo",
     "db.session.commit() es el que realmente escribe en disco",
     "delete(obj) marca para borrar; sin commit nada se persiste",
     "db.session (add / commit / delete)",
     "add encola, commit confirma en disco, delete marca para borrar"),
  ]),
  ("SESION Y LOGIN", [
    ("login_user(user, remember=True) recuerda al usuario; logout_user() lo olvida",
     "Guarda el id del usuario en la sesion (cookie firmada)",
     "Requiere que el modelo herede UserMixin",
     "Flask-Login (login_user)",
     "login_user mete al usuario en la sesion firmada"),
    ("Es un decorador que bloquea la vista a quien no inicio sesion",
     "Redirige al login en vez de mostrar la pagina",
     "Protege la RUTA (no solo esconde el enlace)",
     "@login_required",
     "login_required cierra la puerta a quien no tiene sesion"),
    ("Es el usuario logueado, disponible en cualquier vista y plantilla",
     "current_user.is_authenticated dice si hay sesion activa",
     "No hay que pasarlo como argumento, ya esta a mano",
     "current_user",
     "current_user es el usuario actual, siempre accesible"),
    ("Es la funcion que Flask-Login llama en CADA peticion",
     "Recupera al usuario con User.query.get(int(id)) desde el id de la sesion",
     "Sin ella current_user no se puede reconstruir",
     "@login_manager.user_loader",
     "user_loader rehidrata al usuario desde el id de la sesion"),
    ("LoginManager().init_app(app) activa Flask-Login en la app",
     "login_manager.login_view = 'auth.login' dice a donde mandar si falta sesion",
     "Trabaja junto al user_loader y al UserMixin del modelo",
     "LoginManager",
     "el LoginManager conecta Flask-Login: a donde redirige y como carga al usuario"),
  ]),
  # El video es de 2021 (Flask-SQLAlchemy 2.x / SQLAlchemy 1.x). Estas tarjetas
  # marcan que cambio en Flask-SQLAlchemy 3.x + SQLAlchemy 2.0 (lo actual).
  ("VIEJO (video 2021) vs MODERNO (Flask-SQLAlchemy 3.x)", [
    ("En el video se crea con db.create_all(app=app)",
     "En 3.x create_all() YA NO acepta el argumento app",
     "Ahora hay que envolverlo: with app.app_context(): db.create_all()",
     "Crear tablas hoy",
     "lo moderno: 'with app.app_context(): db.create_all()', sin app="),
    ("En el video se consulta con Model.query.get(id) y Model.query.filter_by(...)",
     "En SQLAlchemy 2.0 el atributo Model.query queda como estilo legacy",
     "Lo nuevo: db.session.get(Model, id) y db.session.execute(db.select(Model))",
     "Consultar hoy (SQLAlchemy 2.0)",
     "lo moderno: db.session.get(User, id) en vez de User.query.get(id)"),
    ("El video pasa generate_password_hash(pw, method='sha256')",
     "El Werkzeug moderno ya usa por defecto un algoritmo fuerte (pbkdf2/scrypt)",
     "Hoy basta con generate_password_hash(pw), sin fijar method",
     "Hashing hoy (Werkzeug)",
     "hoy generate_password_hash(pw) ya elige un algoritmo seguro por defecto"),
    ("El video define los modelos con db.Column(db.Integer, ...)",
     "SQLAlchemy 2.0 introduce tipado: Mapped[int] + mapped_column(...)",
     "El estilo db.Column del video sigue funcionando (no es obligatorio migrar)",
     "Declarar columnas hoy",
     "lo moderno usa Mapped[int] = mapped_column(...), pero db.Column aun vale"),
  ]),
]
