# -*- coding: utf-8 -*-
NAME = "Frontend"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Necesito mostrar y estructurar contenido en pantalla", [
    ("Texto con jerarquía y significado (títulos, secciones, navegación)",
     "HTML semántico (h1-h6, section, article, nav, header/footer)"),
    ("Insertar imagen, enlace, lista o un formulario de entrada",
     "Elementos HTML (img, a, ul/ol, form/input)"),
    ("Que un lector de pantalla y Google entiendan la página",
     "Accesibilidad (a11y): etiquetas semánticas + atributos ARIA"),
  ]),
  ("Se ve horrible y desordenado", [
    ("Dar color, tamaño, fuente y espaciado a un elemento",
     "CSS (selectores + propiedades)"),
    ("Controlar el espacio dentro y fuera de cada elemento",
     "Modelo de caja (content, padding, border, margin)"),
    ("Acomodar elementos en una fila o columna que reparte el espacio",
     "Flexbox (1 dimensión)"),
    ("Acomodar en una cuadrícula de filas y columnas a la vez",
     "Grid (2 dimensiones)"),
    ("Que se vea bien en celular y en pantalla grande",
     "Responsive (media queries + unidades relativas rem/%/vw)"),
    ("Entender por qué un estilo gana sobre otro",
     "Especificidad y cascada"),
  ]),
  ("Quiero que la página reaccione cuando el usuario hace algo", [
    ("Guardar y operar valores: contador, nombre, precio",
     "JavaScript (variables, tipos, funciones, condicionales, bucles)"),
    ("Leer o cambiar un elemento de la página desde código",
     "DOM (document.querySelector, .textContent, .classList)"),
    ("Ejecutar algo justo al hacer clic o teclear",
     "Event listeners (addEventListener)"),
  ]),
  ("La pantalla debe cambiar según lo que pasó antes", [
    ("Tener una única fuente de verdad de la que sale lo que se ve",
     "Estado (UI = f(estado))"),
    ("Representar datos con forma (un árbol, una lista de tareas)",
     "Estructuras de datos (objetos y arrays anidados)"),
    ("Recordar el historial para poder 'regresar'",
     "Pila / stack (push al avanzar, pop al volver)"),
  ]),
  ("Mi JavaScript se volvió un nido de ratas al crecer", [
    ("Reutilizar piezas de UI sin copiar-pegar HTML",
     "Componentes"),
    ("Describir QUÉ mostrar, no CÓMO actualizar el DOM paso a paso",
     "Render declarativo"),
    ("Que la pantalla se redibuje sola cuando cambia el estado",
     "Reactividad"),
    ("Tener el ecosistema para armar y servir el proyecto",
     "Framework (React/Vue/Svelte) + npm + Vite"),
  ]),
  ("Necesito traer y mandar datos al servidor", [
    ("Pedir datos al servidor sin recargar la página",
     "fetch (HTTP desde el cliente)"),
    ("Manejar una operación que termina 'después'",
     "Asíncrono: promesa + async/await"),
    ("Empaquetar los datos para enviarlos y recibirlos",
     "JSON (el sobre universal)"),
    ("Mostrar algo útil si la red falla",
     "Manejo de errores (try/catch + estados de carga/error)"),
  ]),
]

# INTEGRADOR: de las SENALES concretas al concepto + tip verbalizable.
ESTACIONES = [
  ("ESTRUCTURA Y SEMÁNTICA", [
    ("Define la jerarquía del documento con títulos y secciones",
     "Lo leen Google y los lectores de pantalla",
     "No aporta estilo, aporta significado",
     "HTML semántico",
     "el HTML es el esqueleto: dice QUÉ es cada cosa, no cómo se ve"),
    ("Es el árbol de objetos que el navegador construye desde tu HTML",
     "Vive en memoria y se puede modificar con JavaScript",
     "querySelector te da un nodo para leer o cambiar",
     "DOM",
     "el DOM es a la página lo que el DataFrame al CSV: el dato ya parseado y manipulable"),
  ]),
  ("LAYOUT Y CAJA", [
    ("Todo elemento es una caja",
     "De dentro a fuera: contenido, padding, borde, margen",
     "Explica por qué un elemento 'mide más de lo que crees'",
     "Modelo de caja",
     "padding es relleno interno; margin es separación externa"),
    ("Reparte el espacio en UNA dirección: fila o columna",
     "Ideal para una barra de navegación o una fila de botones",
     "Se controla con justify-content / align-items",
     "Flexbox",
     "Flexbox es 1D: piensa en una sola fila o una sola columna"),
    ("Reparte en DOS dimensiones a la vez: filas y columnas",
     "Ideal para el layout general de la página",
     "Se define con grid-template-columns",
     "Grid",
     "Grid es 2D: una cuadrícula completa, como una hoja de cálculo"),
    ("Cuando dos reglas de estilo chocan, una gana",
     "Más específico (#id) vence a menos específico (.clase)",
     "Por eso a veces tu estilo 'no aplica'",
     "Especificidad",
     "id &gt; clase &gt; etiqueta: el selector más específico manda"),
  ]),
  ("REACTIVIDAD E INTERACCIÓN", [
    ("Es la fuente de verdad de la que deriva todo lo visible",
     "Si cambia, la pantalla debe cambiar",
     "La UI sale de él, nunca al revés",
     "Estado (UI = f(estado))",
     "no muevo el DOM a mano: cambio el estado y la UI se recalcula sola"),
    ("Es una función que queda a la espera de un evento",
     "Se dispara con un clic, una tecla o un scroll",
     "Se registra con addEventListener('click', fn)",
     "Event listener",
     "registro una función y el navegador la llama cuando ocurre el evento"),
    ("Pieza de UI reutilizable y autocontenida",
     "Combina estructura + estilo + lógica en un bloque",
     "Se compone como piezas de Lego",
     "Componente",
     "un componente es una función que recibe datos y devuelve UI"),
  ]),
  ("ASINCRONÍA Y RED", [
    ("Es una operación que tarda y no debe congelar la pantalla",
     "Representa un valor que aún no existe pero llegará después",
     "Puede cumplirse (éxito) o rechazarse (error)",
     "Promesa",
     "una promesa es un IOU: 'te pago el valor luego'"),
    ("Espera el valor de una promesa sin bloquear la página",
     "Se lee como código secuencial, de arriba a abajo",
     "Va acompañado de try/catch para los errores",
     "async/await",
     "await es esperar el cobro del IOU sin congelar la fila"),
    ("Es el formato de texto para intercambiar datos",
     "Clave-valor, igual que un objeto o un diccionario",
     "Lo entienden el frontend y el backend por igual",
     "JSON",
     "JSON es el sobre universal: mismo formato en los dos lados de la red"),
  ]),
]
