# -*- coding: utf-8 -*-
# Contenido derivado del video "HTTP protocol" (Backend Engineering,
# youtube.com/watch?v=a3C1DMswClQ): statelessness, mensajes, headers, metodos,
# CORS/preflight, status codes, caching, negociacion de contenido, keep-alive,
# multipart/streaming y TLS.
# Misma metodologia de ejes que el resto de _parts/.
NAME = "Protocolo HTTP"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Quiero entender las dos ideas que sostienen HTTP", [
    ("Que el servidor no recuerde nada de las peticiones anteriores",
     "statelessness (sin estado): responde y se olvida"),
    ("Que cada peticion traiga TODO lo necesario para procesarla",
     "peticiones autocontenidas (metodo, URL, headers, credenciales)"),
    ("Mantener la continuidad aunque el protocolo no recuerde",
     "manejo de estado POR ENCIMA de HTTP: cookies, sesiones, tokens"),
    ("La ventaja de no guardar la sesion en el servidor",
     "simplicidad: no gasta recursos en recordar"),
    ("Repartir peticiones entre varios servidores sin romper nada",
     "escalabilidad: ningun servidor es dueno de la sesion"),
    ("Quien inicia SIEMPRE la comunicacion",
     "el cliente (modelo cliente-servidor); el servidor solo responde"),
  ]),
  ("Quiero saber sobre que viaja HTTP", [
    ("Lo unico que HTTP le exige al transporte",
     "que sea fiable: que no pierda mensajes o avise del error"),
    ("El protocolo de transporte que usa por eso",
     "TCP (orientado a conexion), no UDP"),
    ("La capa del modelo OSI donde trabaja un backend",
     "capa 7, la de aplicacion"),
    ("Donde caen handshakes, TLS y perdida de paquetes",
     "capas de red (dominio de network engineering)"),
    ("Como tratar HTTP y HTTPS mientras aprendes backend",
     "como intercambiables: https es http mas cifrado"),
  ]),
  ("Quiero saber que arreglo cada version de HTTP", [
    ("HTTP 1.0",
     "una conexion NUEVA por cada peticion: lento y caro"),
    ("HTTP 1.1",
     "conexiones persistentes (varias peticiones por la misma conexion TCP), chunked, mejor cache"),
    ("HTTP 2.0",
     "multiplexing, binario en vez de texto, compresion de headers (HPACK), server push"),
    ("HTTP 3.0",
     "sobre QUIC (UDP): conexion mas rapida, menos latencia, sin head-of-line blocking"),
    ("Lo unico que hay que retener de todo esto",
     "cliente y servidor abren una conexion de red y se mandan mensajes"),
  ]),
  ("Quiero leer un mensaje HTTP linea por linea", [
    ("La primera linea de una peticion",
     "metodo + URL del recurso + version (GET /users HTTP/1.1)"),
    ("El dominio al que va dirigida",
     "el header Host"),
    ("Los pares clave-valor con metadatos",
     "los headers"),
    ("Lo que marca que los headers terminaron",
     "una linea en blanco; despues empieza el body"),
    ("Lo que el cliente manda como datos",
     "el request body"),
    ("La primera linea de una respuesta",
     "version + status code + su texto (HTTP/1.1 200 OK)"),
  ]),
  ("Quiero entender POR QUE existen los headers", [
    ("La analogia del paquete que envias",
     "los datos del destinatario van pegados POR FUERA, no dentro"),
    ("Por que no meterlos en el body",
     "habria que abrir el paquete cada vez que alguien necesita leerlos"),
    ("Que son tecnicamente",
     "pares clave-valor de metadatos sobre el mensaje"),
    ("Anadir capacidades nuevas sin tocar el protocolo",
     "extensibilidad: basta con anadir un header"),
    ("Que el cliente influya en COMO responde el servidor",
     "los headers como mando a distancia (formato, idioma, cache, auth)"),
  ]),
  ("Quiero clasificar los headers que veo en la pestana Network", [
    ("Los que hablan del cliente y sus preferencias",
     "request headers: User-Agent, Authorization, Accept"),
    ("Los que hablan del mensaje en si, en peticion y respuesta",
     "general headers: Date, Cache-Control, Connection"),
    ("Los que describen el CUERPO que viaja",
     "representation headers: Content-Type, Content-Length, Content-Encoding, ETag"),
    ("Los que protegen al cliente de ataques",
     "security headers: HSTS, CSP, X-Frame-Options, X-Content-Type-Options"),
    ("Identificar que clase de cliente es (navegador, Postman, movil)",
     "User-Agent"),
    ("Mandar el token que dice quien eres",
     "Authorization"),
  ]),
  ("Quiero saber de que protege cada header de seguridad", [
    ("Forzar que solo se hable por https (sin degradar a http)",
     "HSTS (Strict-Transport-Security)"),
    ("Restringir de donde pueden cargarse scripts, css e imagenes",
     "CSP (Content-Security-Policy), contra cross-site scripting"),
    ("Impedir que tu pagina se incruste en un iframe ajeno",
     "X-Frame-Options, contra clickjacking"),
    ("Impedir que el navegador ADIVINE el tipo de contenido",
     "X-Content-Type-Options, contra MIME sniffing"),
    ("Que JavaScript no pueda leer la cookie",
     "flag HttpOnly (y Secure para que solo viaje por https)"),
  ]),
  ("Quiero declarar la INTENCION de cada peticion", [
    ("Traer datos sin modificar nada en el servidor",
     "GET"),
    ("Crear datos (por eso lleva body)",
     "POST"),
    ("Actualizar solo una parte del recurso",
     "PATCH (reemplazo selectivo)"),
    ("Reemplazar el recurso ENTERO por lo que mandas",
     "PUT (reemplazo completo)"),
    ("Borrar un recurso",
     "DELETE"),
    ("La regla practica entre PUT y PATCH",
     "usa PATCH salvo que de verdad reemplaces todo"),
  ]),
  ("Quiero saber que pasa si repito la misma peticion", [
    ("Poder repetirla y obtener siempre el mismo resultado",
     "idempotente"),
    ("Repetir un GET",
     "idempotente: leer no cambia nada"),
    ("Repetir un PUT",
     "idempotente: reemplaza por el mismo contenido"),
    ("Repetir un DELETE",
     "idempotente: un recurso solo se puede borrar una vez"),
    ("Repetir un POST",
     "NO idempotente: crea una nota nueva cada vez"),
  ]),
  ("Quiero entender por que el navegador bloquea mis llamadas a otro dominio", [
    ("La politica por defecto del navegador",
     "same-origin policy: solo puedes pedir a tu propio origen"),
    ("El mecanismo para permitir excepciones controladas",
     "CORS (cross-origin resource sharing)"),
    ("Que cuenta como origen distinto",
     "otro esquema, dominio O PUERTO (localhost:5173 vs localhost:3000 ya son distintos)"),
    ("El header que el navegador anade solo para decir de donde viene",
     "Origin"),
    ("El header con el que el servidor autoriza",
     "Access-Control-Allow-Origin (el dominio del cliente o *)"),
    ("Que pasa si ese header falta en la respuesta",
     "el navegador BLOQUEA la respuesta: error de CORS"),
    ("Quien impone CORS de verdad",
     "el navegador; el servidor ya proceso la peticion igualmente"),
  ]),
  ("Quiero saber de donde sale esa peticion OPTIONS que no escribi", [
    ("La peticion previa de sondeo que hace el navegador",
     "preflight, con el metodo OPTIONS"),
    ("Condicion 1 para que se dispare",
     "el metodo no es GET, POST ni HEAD (p.ej. PUT o DELETE)"),
    ("Condicion 2",
     "hay headers no simples (Authorization, headers propios)"),
    ("Condicion 3",
     "el Content-Type no es form-urlencoded, multipart ni text/plain (p.ej. application/json)"),
    ("Lo que el preflight PREGUNTA",
     "Access-Control-Request-Method y Access-Control-Request-Headers"),
    ("Lo que el servidor RESPONDE si lo soporta",
     "204 sin body + Allow-Origin, Allow-Methods, Allow-Headers, Max-Age"),
    ("Evitar repetir el preflight en cada peticion",
     "Access-Control-Max-Age (cachea el permiso, p.ej. 24 h)"),
    ("Por que casi todas tus peticiones lo disparan",
     "porque mandas JSON: basta con que se cumpla UNA condicion"),
  ]),
  ("Quiero que el cliente sepa como salio sin leer el body", [
    ("Por que existen los status codes",
     "comunicar el resultado de forma estandarizada, sin adivinar por el contenido"),
    ("Que dice el PRIMER digito",
     "1 informativa, 2 exito, 3 redireccion, 4 culpa del cliente, 5 culpa del servidor"),
    ("Peticion correcta que devuelve el recurso",
     "200 OK"),
    ("Se creo un recurso nuevo (POST, formulario)",
     "201 Created"),
    ("Salio bien pero no hay nada que devolver (preflight, DELETE)",
     "204 No Content"),
    ("Que sea el mismo estandar en python, go, rust o JavaScript",
     "estandarizacion: el codigo es lenguaje universal entre cliente y servidor"),
  ]),
  ("Quiero mandar al cliente a otro sitio o ahorrarle la descarga (3xx)", [
    ("El recurso se movio para siempre a otra URL",
     "301 Moved Permanently (mantiene la compatibilidad de rutas viejas)"),
    ("El recurso esta en otra URL solo por ahora",
     "302 Found (redireccion temporal; sigue usando la original)"),
    ("El recurso no ha cambiado desde tu ultima peticion",
     "304 Not Modified (usa tu copia en cache)"),
  ]),
  ("Quiero elegir el error 4xx correcto (los que mas usaras)", [
    ("El cliente mando datos invalidos o incoherentes",
     "400 Bad Request"),
    ("No mando credenciales, o el token expiro",
     "401 Unauthorized (no se quien eres)"),
    ("Se quien eres, pero no puedes hacer eso",
     "403 Forbidden (borrar el recurso de otro usuario)"),
    ("La URL no existe o el recurso se borro",
     "404 Not Found"),
    ("La ruta existe pero no acepta ese metodo",
     "405 Method Not Allowed"),
    ("Choca con algo que ya existe (carpeta con nombre repetido)",
     "409 Conflict"),
    ("El cliente hace demasiadas peticiones por segundo",
     "429 Too Many Requests (rate limiting)"),
  ]),
  ("Quiero entender los errores 5xx cuando algo revienta", [
    ("Salto una excepcion no controlada en el servidor",
     "500 Internal Server Error (sin dar detalles al cliente, por seguridad)"),
    ("Todavia no soporto esa funcionalidad, pero la soportare",
     "501 Not Implemented"),
    ("El proxy recibio una respuesta invalida del servidor de atras",
     "502 Bad Gateway (tipico de nginx o un load balancer)"),
    ("Estoy caido o en mantenimiento, vuelve luego",
     "503 Service Unavailable"),
    ("El servidor de atras no respondio a tiempo",
     "504 Gateway Timeout"),
  ]),
  ("Quiero que el cliente no vuelva a descargar lo que no cambio", [
    ("Decirle cuanto tiempo puede reutilizar su copia",
     "Cache-Control: max-age"),
    ("Darle una huella (hash) de la respuesta",
     "ETag"),
    ("Decirle cuando se modifico por ultima vez",
     "Last-Modified"),
    ("Que el cliente pregunte: mandamelo solo si cambio el hash",
     "If-None-Match (lleva el ETag que tiene guardado)"),
    ("Que pregunte: mandamelo solo si cambio desde esta fecha",
     "If-Modified-Since"),
    ("La respuesta cuando nada cambio",
     "304 Not Modified, sin body: usa tu copia"),
    ("El riesgo real en produccion",
     "si olvidas actualizar el ETag, el cliente se queda con datos viejos"),
    ("La alternativa moderna",
     "cache en el cliente (react query): el cliente decide cuando refrescar"),
  ]),
  ("Quiero que cliente y servidor acuerden formato, idioma y compresion", [
    ("El formato que quiero recibir",
     "Accept (application/json, application/xml)"),
    ("El idioma que prefiero",
     "Accept-Language (en, es)"),
    ("Las compresiones que soporto",
     "Accept-Encoding (gzip, deflate, br, zstd)"),
    ("Lo que el servidor declara que esta mandando",
     "Content-Type y Content-Encoding"),
    ("Para que sirve comprimir de verdad",
     "el mismo archivo pasa de 26 MB a 3.8 MB de ancho de banda"),
  ]),
  ("Quiero no abrir una conexion nueva en cada peticion", [
    ("Reutilizar la misma conexion TCP para varias peticiones",
     "conexiones persistentes (por defecto desde HTTP 1.1)"),
    ("El header que lo pide explicitamente",
     "Connection: keep-alive"),
    ("Los limites que puede llevar",
     "timeout (cuanto sigue abierta) y max (cuantas peticiones admite)"),
    ("Cerrar la conexion tras la respuesta",
     "Connection: close (el comportamiento por defecto en HTTP 1.0)"),
  ]),
  ("Quiero mover archivos grandes en los dos sentidos", [
    ("Subir un archivo al servidor",
     "peticion multipart: Content-Type multipart/form-data"),
    ("Separar las partes del binario dentro del body",
     "boundary: el delimitador que marca donde empieza y acaba cada parte"),
    ("Recibir una respuesta enorme sin esperar a que acabe",
     "streaming por chunks (chunked transfer)"),
    ("Los headers que lo sostienen",
     "Content-Type: text/event-stream y Connection: keep-alive"),
    ("Lo que hace el cliente mientras llegan",
     "va acumulando los chunks y reconstruyendo el contenido"),
  ]),
  ("Quiero saber que hay debajo de la s de https", [
    ("El protocolo original que cifraba cliente-servidor",
     "SSL (hoy obsoleto por vulnerabilidades)"),
    ("Su sustituto moderno",
     "TLS (version recomendada 1.3)"),
    ("Como se comprueba que el servidor es quien dice ser",
     "certificados"),
    ("Que es https exactamente",
     "HTTP corriendo sobre TLS: mismo protocolo, cifrado en transito"),
  ]),
]

# INTEGRADOR: de las SENALES concretas (discriminadores) al concepto + tip verbalizable.
ESTACIONES = [
  ("LAS DOS IDEAS DE HTTP", [
    ("El servidor responde y se olvida de la peticion",
     "La siguiente peticion la trata como un evento nuevo y sin relacion",
     "Por eso cada peticion debe traer sus credenciales otra vez",
     "Statelessness",
     "HTTP no tiene memoria: cada peticion llega como si fuera la primera"),
    ("Simplicidad: el servidor no gasta recursos en recordar sesiones",
     "Escalabilidad: cualquier servidor puede atender cualquier peticion",
     "Si un servidor se cae, no hay sesion que restaurar",
     "Beneficios del modelo sin estado",
     "sin memoria no hay nada que sincronizar ni que perder"),
    ("El cliente (navegador o app) SIEMPRE inicia la comunicacion",
     "El servidor aloja el recurso y espera; nunca llama primero",
     "El cliente debe aportar toda la info que el servidor necesita",
     "Modelo cliente-servidor",
     "en HTTP el servidor nunca llama: solo contesta a quien le habla"),
  ]),
  ("TRANSPORTE Y CAPAS", [
    ("HTTP no exige que el transporte tenga conexion: exige que sea FIABLE",
     "Entre TCP y UDP, TCP es el fiable, asi que HTTP se apoya en TCP",
     "Handshake y paquetes son capas de abajo, de red",
     "HTTP sobre TCP",
     "HTTP pide fiabilidad, y quien la da es TCP"),
    ("El backend trabaja en la capa 7 del modelo OSI, la de aplicacion",
     "TLS, handshakes y perdida de paquetes viven en capas mas bajas",
     "https es http mas cifrado: los principios son los mismos",
     "Capa de aplicacion",
     "tu trabajas en la capa 7; lo de abajo es ingenieria de redes"),
  ]),
  ("LAS VERSIONES DE HTTP", [
    ("En 1.0 cada peticion abria y cerraba su propia conexion",
     "En 1.1 la conexion TCP se reutiliza para varias peticiones",
     "1.1 anade tambien chunked transfer y mejor cache",
     "1.0 vs 1.1",
     "1.1 dejo de tirar la conexion despues de cada peticion"),
    ("2.0 permite varias peticiones a la vez por una sola conexion (multiplexing)",
     "Manda binario en vez de texto y comprime los headers",
     "3.0 va sobre QUIC (UDP): conecta antes y aguanta mejor la perdida de paquetes",
     "2.0 vs 3.0",
     "2.0 multiplexa sobre TCP; 3.0 se muda a UDP para quitar el bloqueo"),
  ]),
  ("ANATOMIA DEL MENSAJE", [
    ("La primera linea de la PETICION lleva metodo, URL y version",
     "La primera linea de la RESPUESTA lleva version, status code y su texto",
     "El header Host dice a que dominio va dirigida",
     "Linea inicial",
     "la peticion abre con el metodo; la respuesta abre con el codigo"),
    ("Despues de los headers hay una LINEA EN BLANCO",
     "Esa linea en blanco marca que empieza el body",
     "El body lleva los datos; los headers, los metadatos",
     "Headers, linea en blanco y body",
     "la linea vacia es la frontera entre metadatos y datos"),
  ]),
  ("POR QUE EXISTEN LOS HEADERS", [
    ("Cuando mandas un paquete, los datos del destinatario van POR FUERA",
     "Si estuvieran dentro, habria que abrirlo cada vez que alguien los necesita",
     "Los headers son esa etiqueta: metadatos legibles sin tocar el contenido",
     "La analogia del paquete",
     "los headers son la etiqueta pegada por fuera, no el contenido"),
    ("Se pueden anadir headers nuevos sin cambiar el protocolo",
     "Un header cambia el comportamiento de toda la interaccion",
     "Por eso HTTP absorbe usos nuevos (seguridad, cache, formatos)",
     "Extensibilidad",
     "HTTP crece anadiendo headers, no cambiando el protocolo"),
    ("Accept hace que el servidor mande HTML o JSON segun pidas",
     "Cache-Control decide cuanto vive la copia en el cliente",
     "Authorization decide si te dejan pasar",
     "Headers como mando a distancia",
     "con headers el cliente dirige como le responden"),
  ]),
  ("LOS CUATRO TIPOS DE HEADERS", [
    ("User-Agent dice que clase de cliente eres",
     "Authorization lleva tus credenciales",
     "Accept dice que formato esperas",
     "Request headers",
     "los request headers describen al cliente: quien es, que trae y que espera"),
    ("Date, Cache-Control y Connection aparecen en peticion Y respuesta",
     "No hablan del contenido, hablan del mensaje mismo",
     "Son informacion de transporte y de cache",
     "General headers",
     "los general headers hablan del mensaje, no de su cuerpo"),
    ("Content-Type dice el tipo de medio del cuerpo",
     "Content-Length su tamano en bytes y Content-Encoding su compresion",
     "ETag es la huella del cuerpo, usada para cache",
     "Representation headers",
     "los representation headers describen el cuerpo que viaja"),
  ]),
  ("HEADERS DE SEGURIDAD", [
    ("HSTS obliga a hablar solo por https (evita degradar a http)",
     "CSP limita de donde se cargan scripts, css e imagenes",
     "CSP existe sobre todo contra cross-site scripting",
     "HSTS y CSP",
     "HSTS asegura el canal; CSP asegura de donde viene el codigo"),
    ("X-Frame-Options impide que tu pagina se incruste en un iframe (clickjacking)",
     "X-Content-Type-Options impide que el navegador adivine el tipo (MIME sniffing)",
     "Los flags HttpOnly y Secure protegen la cookie: ni JS la lee ni viaja sin cifrar",
     "Anti-iframe, anti-sniffing y cookies",
     "cada header de seguridad cierra un ataque concreto"),
  ]),
  ("METODOS: LA INTENCION", [
    ("GET trae datos y no debe modificar nada",
     "POST crea datos y por eso lleva body",
     "DELETE borra el recurso",
     "GET, POST y DELETE",
     "el metodo declara la intencion antes de mirar la ruta"),
    ("PATCH actualiza SOLO lo que mandas (reemplazo selectivo)",
     "PUT reemplaza el recurso ENTERO por lo que mandas",
     "La regla: usa PATCH salvo que de verdad reemplaces todo",
     "PATCH vs PUT",
     "PATCH retoca; PUT sustituye el recurso completo"),
  ]),
  ("IDEMPOTENCIA", [
    ("Repetir un GET siempre devuelve lo mismo: solo lee",
     "Repetir un PUT deja el recurso igual: reemplaza por lo mismo",
     "Repetir un DELETE no cambia nada: solo se borra una vez",
     "Metodos idempotentes",
     "idempotente es repetir sin que el resultado cambie"),
    ("Repetir un POST crea una nota nueva cada vez",
     "Misma peticion, resultados distintos",
     "Por eso el doble clic en 'enviar' duplica registros",
     "POST no es idempotente",
     "POST crea otra cosa cada vez que lo repites"),
  ]),
  ("SAME-ORIGIN Y CORS", [
    ("Por defecto el navegador solo deja pedir a tu MISMO origen",
     "Distinto esquema, dominio O PUERTO ya es otro origen",
     "localhost:5173 pidiendo a localhost:3000 ya es cross-origin",
     "Same-origin policy",
     "hasta un puerto distinto convierte la peticion en cross-origin"),
    ("El navegador anade solo el header Origin con tu procedencia",
     "El servidor autoriza con Access-Control-Allow-Origin (tu dominio o *)",
     "Si ese header falta, el navegador bloquea la respuesta",
     "Origin vs Access-Control-Allow-Origin",
     "Origin lo pone el navegador; Allow-Origin es el permiso del servidor"),
    ("En un error de CORS el servidor SI recibio y proceso la peticion",
     "Lo que se bloquea es la RESPUESTA, ya de vuelta",
     "Quien bloquea es el navegador, no el servidor",
     "Quien impone CORS",
     "CORS no protege al servidor: el navegador te corta la respuesta"),
  ]),
  ("EL PREFLIGHT (OPTIONS)", [
    ("Se dispara si el metodo no es GET, POST ni HEAD",
     "O si hay headers no simples, como Authorization",
     "O si el Content-Type es application/json",
     "Cuando hay preflight",
     "basta con que se cumpla UNA de las tres; por eso el JSON casi siempre lo dispara"),
    ("El preflight va con metodo OPTIONS y sin body: es una consulta",
     "Pregunta con Access-Control-Request-Method y -Request-Headers",
     "Es decir: soportas este metodo y estos headers para esta ruta",
     "Que pregunta el preflight",
     "OPTIONS pregunta permiso antes de mandar la peticion de verdad"),
    ("El servidor contesta 204 (sin contenido) con los headers de permiso",
     "Allow-Origin, Allow-Methods y Allow-Headers son los tres checks del navegador",
     "Access-Control-Max-Age cachea ese permiso y evita repetir el preflight",
     "Que responde el servidor",
     "204 mas tres permisos; Max-Age dice cuanto valen sin volver a preguntar"),
  ]),
  ("FAMILIAS DE STATUS CODES", [
    ("El primer digito clasifica: 1 informativa, 2 exito, 3 redireccion",
     "4 es culpa del cliente y 5 es culpa del servidor",
     "Sin el codigo, el cliente tendria que adivinar leyendo el body",
     "El primer digito",
     "el primer digito dice de quien es la culpa antes de leer nada"),
    ("200 OK: salio bien y aqui va el recurso",
     "201 Created: se creo algo nuevo (POST, formulario)",
     "204 No Content: salio bien pero no hay nada que devolver (preflight, DELETE)",
     "La familia 2xx",
     "200 devuelve, 201 crea, 204 confirma sin devolver nada"),
    ("El estandar es el mismo en python, go, rust o JavaScript",
     "El cliente puede reaccionar sin conocer el servidor",
     "Un 401 le basta para cerrar sesion y pedir login otra vez",
     "Estandarizacion",
     "el status code es el idioma comun entre cualquier cliente y cualquier servidor"),
  ]),
  ("REDIRECCIONES (3XX)", [
    ("301 es permanente: la ruta se movio para siempre, usa la nueva",
     "302 es temporal: por ahora ve alli, pero sigue usando la original",
     "301 mantiene vivas las rutas viejas sin romper a nadie",
     "301 vs 302",
     "301 es mudanza definitiva; 302 es estar de paso"),
    ("304 no es una redireccion de ruta: dice que el recurso no cambio",
     "Llega sin body, para que uses tu copia en cache",
     "Aparece cuando preguntaste con ETag o Last-Modified",
     "304 Not Modified",
     "304 no te manda a otro sitio: te manda a tu propia cache"),
  ]),
  ("ERRORES DEL CLIENTE (4XX)", [
    ("400: los datos venian mal (esperabas numero y llego texto)",
     "401: no se quien eres (falta el token o expiro)",
     "403: se quien eres, pero no puedes hacer eso",
     "400 vs 401 vs 403",
     "400 es dato malo, 401 es sin identificar, 403 es identificado y sin permiso"),
    ("404: la URL no existe o el recurso se borro",
     "405: la ruta existe pero no acepta ese metodo (tipico typo de PUT por PATCH)",
     "409: choca con algo que ya existe, como una carpeta con nombre repetido",
     "404 vs 405 vs 409",
     "404 no esta, 405 esta pero no asi, 409 ya esta y choca"),
    ("429: demasiadas peticiones en poco tiempo",
     "Se usa para hacer rate limiting (p.ej. 60 por segundo)",
     "Protege al servidor de que un cliente lo sature",
     "429 Too Many Requests",
     "429 no es un error tuyo de datos: es que vas demasiado rapido"),
  ]),
  ("ERRORES DEL SERVIDOR (5XX)", [
    ("500: salto una excepcion no controlada dentro del servidor",
     "Se responde sin detalles, por seguridad",
     "501 en cambio dice: aun no lo soporto, pero lo soportare",
     "500 vs 501",
     "500 es que se rompio; 501 es que todavia no existe"),
    ("502: el proxy recibio una respuesta INVALIDA del servidor de atras",
     "504: el servidor de atras no respondio A TIEMPO",
     "Los dos los devuelve el proxy (nginx, load balancer), no tu codigo",
     "502 vs 504",
     "502 es respuesta mala; 504 es respuesta que nunca llego"),
    ("503: el servicio esta caido o en mantenimiento",
     "Le dice al cliente que reintente mas tarde",
     "Tipico en picos de trafico o despliegues",
     "503 Service Unavailable",
     "503 es 'ahora no, vuelve luego'"),
  ]),
  ("CACHING CON HEADERS", [
    ("Cache-Control: max-age dice cuantos segundos vale la copia",
     "ETag es la huella (hash) de la respuesta",
     "Last-Modified es la fecha del ultimo cambio",
     "Los tres headers de cache",
     "max-age dice cuanto dura; ETag y Last-Modified dicen si cambio"),
    ("If-None-Match manda el ETag guardado: mandamelo solo si cambio el hash",
     "If-Modified-Since manda la fecha: mandamelo solo si cambio desde entonces",
     "Los pone el CLIENTE en la siguiente peticion",
     "Peticion condicional",
     "el cliente pregunta 'ha cambiado?' antes de volver a descargar"),
    ("Si nada cambio el servidor responde 304, sin body",
     "Si algo cambio responde 200 con el recurso y un ETag nuevo",
     "Si olvidas actualizar el ETag, el cliente se queda con datos viejos",
     "304 vs 200 en cache",
     "304 ahorra la descarga; el peligro es un ETag que no se actualiza"),
  ]),
  ("NEGOCIACION Y COMPRESION", [
    ("Accept pide el formato (JSON o XML)",
     "Accept-Language pide el idioma (en o es)",
     "Accept-Encoding declara que compresiones entiende el cliente",
     "Negociacion de contenido",
     "el cliente dice que prefiere y el servidor sirve la version que encaja"),
    ("El servidor responde con Content-Type y Content-Encoding: gzip",
     "El mismo archivo pasa de 26 MB sin comprimir a 3.8 MB con gzip",
     "El navegador lo descomprime y obtiene el mismo contenido",
     "Compresion HTTP",
     "comprimir no cambia el contenido: cambia lo que se paga en ancho de banda"),
  ]),
  ("CONEXIONES PERSISTENTES", [
    ("Abrir y cerrar una conexion TCP cuesta tiempo y recursos",
     "Desde HTTP 1.1 la conexion se reutiliza por defecto",
     "Connection: keep-alive lo pide explicitamente, con timeout y max",
     "Keep-alive",
     "keep-alive deja la puerta abierta en vez de tocar el timbre cada vez"),
    ("Connection: close cierra la conexion tras la respuesta",
     "Era el comportamiento por defecto en HTTP 1.0",
     "En 1.1 hay que pedirlo explicitamente",
     "Connection: close",
     "close vuelve al modelo viejo: una conexion, una peticion"),
  ]),
  ("ARCHIVOS GRANDES", [
    ("Para subir un archivo el Content-Type es multipart/form-data",
     "El binario viaja en PARTES dentro del mismo body",
     "El parametro boundary es el delimitador que separa esas partes",
     "Multipart y boundary",
     "multipart parte el archivo y el boundary marca donde acaba cada parte"),
    ("Para bajar algo enorme el servidor manda chunks segun los tiene",
     "Content-Type: text/event-stream y Connection: keep-alive lo sostienen",
     "El cliente va acumulando los trozos y reconstruye el contenido",
     "Streaming por chunks",
     "streaming no espera al archivo entero: manda trozos por una conexion abierta"),
  ]),
  ("SSL, TLS Y HTTPS", [
    ("SSL fue el protocolo original de cifrado cliente-servidor",
     "Quedo obsoleto por vulnerabilidades y lo sustituyo TLS (hoy 1.3)",
     "TLS usa certificados para probar que el servidor es quien dice ser",
     "SSL vs TLS",
     "SSL es el antepasado; TLS es lo que de verdad cifra hoy"),
    ("https es HTTP corriendo sobre TLS",
     "El protocolo es el mismo: cambia que va cifrado en transito",
     "Protege credenciales y datos de ser interceptados",
     "Que es https",
     "la s de https es TLS: mismo protocolo, canal cifrado"),
  ]),
]
