# -*- coding: utf-8 -*-
"""Machine Learning aplicado: lo practico para levantar un proyecto de vision
medica (clasificador de OCT retiniana) desde cero.

Cubre el ciclo completo: entorno -> librerias -> instalacion -> de donde salen
los datos -> como se bajan y se verifican -> como se protege el repo -> que
decisiones hay que tomar sobre el modelo.
"""
NAME = "Machine Learning"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Necesito un espacio donde esto viva sin romperme la computadora", [
    ("Aislar las librerias de este proyecto de las del resto del sistema",
     "Entorno virtual (venv)"),
    ("Crear ese entorno dentro de la carpeta del proyecto",
     "python3 -m venv .venv"),
    ("Hacer que python y pip apunten a los de adentro y no a los del sistema",
     "source .venv/bin/activate"),
    ("Confirmar que de verdad estoy dentro del entorno",
     "El prompt muestra (.venv) · which python"),
    ("Dejar constancia exacta de que instale y en que version",
     "requirements.txt (generado con pip freeze)"),
    ("Reinstalar lo mismo en otra maquina o dentro de un ano",
     "pip install -r requirements.txt"),
    ("Evitar que el entorno y 5 GB de datos acaben en GitHub",
     ".gitignore"),
    ("Salir del entorno sin cerrar la terminal",
     "deactivate"),
  ]),

  ("Que libreria hace que? No quiero instalar a ciegas", [
    ("Construir redes neuronales y entrenarlas (tensores y gradientes)",
     "PyTorch (torch)"),
    ("Redes de vision ya preentrenadas, transformaciones de imagen y lectura de carpetas",
     "torchvision"),
    ("Metricas de evaluacion: matriz de confusion, sensibilidad, AUC",
     "scikit-learn"),
    ("Ver las imagenes y graficar la curva de perdida",
     "matplotlib"),
    ("Manejar la tabla de resultados de cada experimento",
     "pandas"),
    ("Bajar datasets publicos desde la terminal, de forma repetible",
     "kaggle (CLI)"),
    ("Cargar un dataset publico en una sola linea de Python",
     "datasets (Hugging Face)"),
    ("Ver en que zona de la imagen se apoyo el modelo para decidir",
     "pytorch-grad-cam"),
    ("No quedarme mirando una terminal muda mientras entrena",
     "tqdm (barra de progreso)"),
  ]),

  ("Como instalo, y bajo que condiciones?", [
    ("Instalar dentro del proyecto y no en el sistema",
     "pip, SIEMPRE con el venv ya activado"),
    ("Actualizar la herramienta antes de instalar nada pesado",
     "pip install --upgrade pip"),
    ("PyTorch se instala distinto segun haya GPU o no",
     "Elegir el indice: whl/cpu vs CUDA"),
    ("Saber si tengo GPU antes de elegir",
     "nvidia-smi (sistema) · torch.cuda.is_available() (Python)"),
    ("Confirmar que quedo instalado y en que version",
     "pip list · import torch; torch.__version__"),
    ("Que la instalacion no dependa de mi memoria",
     "Congelarla en requirements.txt"),
  ]),

  ("De donde saco imagenes medicas etiquetadas, y por que importa?", [
    ("Plataforma con datasets ya etiquetados y API de terminal",
     "Kaggle"),
    ("Por que Kaggle y no bajar a mano desde el navegador",
     "Es scriptable, versionado y reproducible: el comando queda escrito en el README"),
    ("Alternativa que se carga en una linea desde Python",
     "Hugging Face Hub (load_dataset)"),
    ("Los datos originales tal como los publicaron los autores",
     "Mendeley Data / material suplementario del articulo"),
    ("Datos clinicos de acceso controlado, con permiso",
     "PhysioNet / solicitud directa al autor"),
    ("Quien puso las etiquetas define el techo de tu modelo",
     "Procedencia y estandar de referencia (gold standard)"),
    ("Un dataset sin licencia clara no se puede publicar encima",
     "Revisar la licencia ANTES de construir sobre el"),
    ("Saber si el dataset ya trae las particiones hechas",
     "Carpetas train / val / test que provee el autor"),
  ]),

  ("Como bajo los datos y confirmo que llegaron bien?", [
    ("Autorizar a la terminal a actuar con mi cuenta",
     "Token kaggle.json en ~/.kaggle con chmod 600"),
    ("Buscar el dataset sin salir de la terminal",
     'kaggle datasets list -s "retinal oct"'),
    ("Bajarlo a una carpeta concreta",
     "kaggle datasets download -d owner/slug -p carpeta"),
    ("Descomprimirlo sin llenar el directorio actual de archivos sueltos",
     "unzip -q archivo.zip -d carpeta"),
    ("Confirmar que el ZIP no llego corrupto",
     "unzip -t (y comparar el tamano esperado)"),
    ("Ver la estructura de carpetas sin imprimir 84.000 rutas",
     "find ... -maxdepth 4 -type d"),
    ("Contar cuantas imagenes hay por clase: esta balanceado?",
     "find + wc -l, un conteo por carpeta"),
    ("Saber cuanto ocupa en disco lo que baje",
     "du -sh"),
    ("Mirar una imagen de cada clase ANTES de entrenar nada",
     "Abrirlas con matplotlib (paso 1 innegociable)"),
  ]),

  ("Como protejo el repositorio?", [
    ("Que el entorno y los datos nunca entren al historial",
     ".gitignore desde el PRIMER commit (.venv/, datos/, *.pth)"),
    ("Que la credencial de Kaggle nunca viva dentro del proyecto",
     "kaggle.json fuera del repo, en ~/.kaggle"),
    ("Verificar que se va a subir antes de subirlo",
     "git status · git add -n ."),
    ("Comprobar que una carpeta si esta siendo ignorada",
     "git check-ignore -v datos/"),
    ("Sacar del rastreo algo ya commiteado por error",
     "git rm --cached -r datos/"),
    ("Si un secreto ya se subio, borrar el archivo no basta",
     "Rotar/revocar la credencial: el historial la conserva"),
    ("GitHub rechaza archivos de mas de 100 MB",
     "Los datos nunca van al repo; van las instrucciones para bajarlos"),
    ("Que el repo siga siendo reproducible sin los datos dentro",
     "README con el comando exacto de descarga"),
  ]),

  ("Que decisiones hay que tomar sobre el modelo?", [
    ("Entrenar desde cero o partir de una red ya entrenada",
     "Transfer learning (con pocos datos, siempre transfer)"),
    ("Cuanto de la red preentrenada dejo quieto",
     "Congelar capas (freeze) vs fine-tuning completo"),
    ("Que arquitectura base elijo",
     "ResNet18 (pequena y rapida) vs EfficientNet vs ViT (exige mas datos)"),
    ("Para que sirve cada particion de los datos",
     "train: aprender · validacion: decidir · test: juzgar UNA sola vez"),
    ("Cuantas imagenes ve antes de corregirse",
     "Batch size (lo limita tu memoria)"),
    ("Cuantas vueltas completas da al dataset",
     "Epochs"),
    ("De que tamano es cada paso de correccion",
     "Learning rate (el hiperparametro que mas rompe)"),
    ("Como se mide el error en clasificacion multiclase",
     "Funcion de perdida: CrossEntropyLoss"),
    ("Quien aplica esa correccion a los pesos",
     "Optimizador (Adam, SGD)"),
    ("Que metrica reporto en un problema clinico",
     "Sensibilidad y especificidad POR CLASE, no accuracy sola"),
    ("Que hago si una clase tiene cuatro veces mas imagenes que otra",
     "Desbalance: pesos de clase o submuestreo"),
    ("Como se que memorizo en vez de aprender",
     "Overfitting: la perdida de validacion sube mientras la de train baja"),
    ("Como se que acerto por la razon correcta",
     "Grad-CAM: mirar donde se apoyo"),
  ]),
]

# INTEGRADOR: de las SENALES concretas al concepto + tip verbalizable.
ESTACIONES = [
  ("ENTORNO", [
    ("Vive dentro de la carpeta del proyecto",
     "Hace que pip instale ahi y no en el sistema",
     "Si lo borras entero no rompes nada mas",
     "Entorno virtual (venv)",
     "el venv es el botiquin propio del proyecto: lo que guardas aqui no afecta a los otros"),
    ("Cambia tu prompt a (.venv)",
     "Hace que which python apunte dentro del proyecto",
     "Hay que repetirlo en cada terminal nueva",
     "Activar el entorno (source .venv/bin/activate)",
     "activar no instala nada: solo cambia a que python le estas hablando"),
    ("Es una lista de librerias con su version exacta",
     "Se genera con pip freeze",
     "Otra persona reproduce tu instalacion con un solo comando",
     "requirements.txt",
     "requirements.txt es la receta: sin ella, en tres meses tu propio proyecto no corre"),
    ("Es un archivo de texto en la raiz del repo",
     "Dice que NO debe rastrear git",
     "Tiene que existir antes del primer commit",
     ".gitignore",
     "el .gitignore es la puerta: si los datos ya entraron, cerrarla despues no los saca"),
  ]),

  ("LIBRERIAS", [
    ("Trabaja con tensores y calcula gradientes",
     "Es quien realmente entrena la red",
     "Se instala distinto segun tengas GPU o no",
     "PyTorch",
     "torch es el motor: pone los numeros y las derivadas"),
    ("Trae ResNet y EfficientNet ya entrenadas",
     "Incluye transforms para redimensionar y normalizar",
     "ImageFolder lee carpetas como si fueran clases",
     "torchvision",
     "torchvision es el maletin de vision: modelos prestados mas como prepararles la imagen"),
    ("No entrena absolutamente nada",
     "Da matriz de confusion, sensibilidad y AUC",
     "Se usa DESPUES de que el modelo ya predijo",
     "scikit-learn",
     "sklearn no entrena tu red: la juzga"),
    ("Se autentica con un token guardado en ~/.kaggle",
     "Baja el dataset con un comando de una linea",
     "Deja la descarga escrita y repetible en el README",
     "Kaggle CLI",
     "bajar a mano no es reproducible; el comando si"),
  ]),

  ("DATOS", [
    ("Lee una carpeta por clase",
     "El nombre de la carpeta ES la etiqueta",
     "Devuelve pares (imagen, etiqueta)",
     "ImageFolder",
     "ImageFolder confia en tus carpetas: si estan mal nombradas, tus etiquetas estan mal"),
    ("Entrega las imagenes en lotes",
     "shuffle=True mezcla el orden en cada epoch",
     "El tamano del lote lo limita tu memoria",
     "DataLoader",
     "el DataLoader es la banda transportadora: decide de a cuantas llegan y en que orden"),
    ("Redimensiona todo a 224x224",
     "Resta la media y divide por la desviacion de ImageNet",
     "Sin esto la red preentrenada ve numeros que no reconoce",
     "transforms (Resize + Normalize)",
     "la red prestada exige su mismo formato de entrada: normalizar es hablarle en su idioma"),
    ("Uno sirve para aprender",
     "Otro para elegir los hiperparametros",
     "El tercero se toca una sola vez, al final",
     "Train / Validacion / Test",
     "el test es el examen: si lo miras mientras estudias, deja de medir nada"),
    ("El mismo paciente aparece en train y en test",
     "Las metricas salen sospechosamente altas",
     "El modelo no reproduce fuera de tu dataset",
     "Fuga de datos (data leakage)",
     "si el modelo ya vio a ese paciente no lo esta diagnosticando: lo esta recordando"),
  ]),

  ("MODELO", [
    ("Parte de una red ya entrenada con millones de fotos",
     "Solo le cambias la ultima capa",
     "Funciona incluso con pocos datos propios",
     "Transfer learning",
     "no le ensenas a ver desde cero: le ensenas a nombrar lo que ya ve"),
    ("Dejas quietas las capas de abajo",
     "Solo se actualiza la ultima",
     "Entrena rapido y sobreajusta menos cuando hay pocos datos",
     "Congelar capas (freeze)",
     "congelar es decirle: ya sabes ver bordes y texturas, no lo desaprendas"),
    ("Define el tamano del paso de correccion",
     "Si es muy alto la perdida explota",
     "Si es muy bajo no aprende nunca",
     "Learning rate",
     "el lr es el largo del paso: las zancadas te tiran, los pasos de hormiga no llegan"),
    ("Cuenta cuantas vueltas completas dio al dataset",
     "Pocas: no alcanzo a aprender",
     "Muchas: empieza a memorizar",
     "Epochs",
     "las epochs son repasos: los justos consolidan, los de mas memorizan"),
    ("Mide que tan mal predijo",
     "Es exactamente lo que el entrenamiento intenta bajar",
     "En clasificacion multiclase es la estandar",
     "CrossEntropyLoss",
     "la perdida es la nota del examen; entrenar es intentar bajarla"),
  ]),

  ("EVALUACION", [
    ("Es una tabla de lo que era contra lo que predijo",
     "La diagonal son los aciertos",
     "Muestra QUE confunde con QUE, no solo cuanto falla",
     "Matriz de confusion",
     "el accuracy dice cuanto falla; la matriz dice con quien se equivoca"),
    ("Una clase concentra el 90% de las imagenes",
     "El modelo aprende a predecir siempre esa clase",
     "El accuracy sale alto y el modelo es inutil",
     "Desbalance de clases",
     "con clases desbalanceadas el accuracy miente: pide sensibilidad por clase"),
    ("La perdida de entrenamiento sigue bajando",
     "La de validacion empieza a subir",
     "Aprendio tu set concreto, no el problema",
     "Overfitting",
     "overfitting es memorizar el examen anterior: perfecto ahi, perdido en el nuevo"),
    ("Pinta un mapa de calor encima de la imagen",
     "Muestra que pixeles pesaron en la decision",
     "Si senala el borde del aparato, acerto por la razon equivocada",
     "Grad-CAM",
     "Grad-CAM hace la unica pregunta que importa en clinica: miro la retina o miro la maquina?"),
  ]),
]
