# -*- coding: utf-8 -*-
# Contenido derivado del tutorial de pandas (Tech With Tim,
# youtube.com/watch?v=EXIgjIBu4EU).
# Misma metodologia de ejes que frontend/backend/data/flask/python.
NAME = "Pandas"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Quiero empezar a trabajar con datos tabulares en Python", [
    ("Instalar la libreria",
     "pip install pandas (o uv add pandas)"),
    ("Importarla con el alias estandar",
     "import pandas as pd"),
    ("La estructura 2D tipo hoja de calculo (filas y columnas)",
     "DataFrame"),
    ("Una sola fila o columna (1D) con etiquetas",
     "Series"),
    ("Por que es rapida",
     "esta construida sobre NumPy (C), no sobre listas de Python"),
  ]),
  ("Quiero cargar mis datos", [
    ("Cargar un CSV (valores separados por comas)",
     "pd.read_csv('orders.csv')"),
    ("Cargar una hoja de Excel",
     "pd.read_excel(...)"),
    ("Crear un DataFrame a mano",
     "pd.DataFrame(diccionario)"),
    ("Saber que cada fila recibe un identificador al cargar",
     "indice automatico 0, 1, 2..."),
  ]),
  ("Quiero echar un vistazo rapido al DataFrame", [
    ("Ver las primeras 5 filas",
     "df.head()"),
    ("Ver las ultimas 5 filas",
     "df.tail()"),
    ("Info general: filas, columnas, tipos y nulos",
     "df.info()"),
    ("Estadisticas descriptivas (media, percentiles)",
     "df.describe()"),
    ("Listar los nombres de las columnas",
     "df.columns"),
    ("Ver el rango del indice",
     "df.index"),
  ]),
  ("Quiero sacar columnas o filas concretas", [
    ("Sacar UNA columna (devuelve Series)",
     "df['country']"),
    ("Sacar VARIAS columnas (devuelve DataFrame)",
     "df[['country', 'product']]"),
    ("Sacar una fila por su POSICION numerica",
     "df.iloc[0]"),
    ("Localizar fila(s) por una etiqueta o condicion",
     "df.loc[...]"),
  ]),
  ("Quiero filtrar las filas que cumplen una condicion", [
    ("Filtrar por el valor de una columna",
     "df[df['category'] == 'Electronics']"),
    ("Combinar condiciones (ambas / alguna)",
     "&amp; (and) / | (or), cada una entre parentesis"),
    ("Comparar valores",
     "operadores &gt; &lt; &gt;= &lt;= !="),
    ("Filtrar por texto que empieza o termina con algo",
     "df['col'].str.startswith(...) / .endswith(...)"),
    ("Filtrar por estar en una lista de valores",
     "df['col'].isin([...])"),
    ("Invertir un filtro (lo que NO cumple)",
     "~ (tilde) delante de la condicion"),
  ]),
  ("Quiero actualizar valores", [
    ("Cambiar una celda localizando la fila por condicion",
     "df.loc[df['name'] == 'Anna', 'product'] = 'Tim'"),
    ("Cambiar toda una columna a mayusculas",
     "df['country'] = df['country'].str.upper()"),
    ("Cambiar el nombre de una columna",
     "df.rename(columns={...}, inplace=True)"),
  ]),
  ("Quiero limpiar y borrar datos", [
    ("Borrar una fila por su indice",
     "df = df.drop(39)"),
    ("Quitar filas con valores nulos/faltantes",
     "df.dropna()"),
    ("Rellenar los nulos con un valor",
     "df.fillna(0, inplace=True)"),
    ("Modificar el original en vez de devolver uno nuevo",
     "inplace=True"),
  ]),
  ("Quiero analizar y resumir los datos", [
    ("Contar cuantas veces aparece cada valor",
     "df['country'].value_counts()"),
    ("Agrupar y resumir (sumar precio por pais)",
     "df.groupby('country')['price'].sum()"),
    ("Ordenar por una columna",
     "df.sort_values('price', ascending=False)"),
  ]),
  ("Quiero guardar el resultado", [
    ("Guardar el DataFrame a un CSV",
     "df.to_csv('new_file.csv', index=False)"),
    ("Decidir si incluir la columna de indices",
     "index=True / index=False"),
  ]),
]

# INTEGRADOR: de las SENALES concretas (discriminadores) al concepto + tip verbalizable.
ESTACIONES = [
  ("ESTRUCTURAS DE PANDAS", [
    ("DataFrame es 2D: filas y columnas, como una hoja de calculo",
     "Series es 1D: una sola columna o fila con etiquetas",
     "Indexar UNA columna da Series; indexar varias da DataFrame",
     "DataFrame vs Series",
     "DataFrame = tabla 2D; Series = una columna/fila 1D"),
    ("Esta construida sobre NumPy (en C) por debajo",
     "Es mas rapida que una lista 2D de Python",
     "Por eso sus tipos (int64, float64, object) no son los de Python puro",
     "Base NumPy",
     "pandas corre sobre NumPy en C: mas veloz que listas"),
  ]),
  ("CARGAR DATOS", [
    ("pd.read_csv('archivo.csv') vuelca un CSV en un DataFrame",
     "CSV = valores separados por comas",
     "Al cargar, cada fila recibe un indice automatico 0, 1, 2...",
     "pd.read_csv",
     "read_csv mete el CSV en un DataFrame con indice automatico"),
    ("pd.DataFrame(diccionario) crea uno a mano",
     "pd.read_excel carga una hoja de Excel",
     "El alias estandar al importar es 'as pd'",
     "Otras formas de cargar",
     "DataFrame(dict) a mano; read_excel para Excel"),
  ]),
  ("EXPLORAR", [
    ("head() muestra las PRIMERAS 5 filas",
     "tail() muestra las ULTIMAS 5 filas",
     "Sirven para ojear sin imprimir todo el DataFrame",
     "head / tail",
     "head = primeras 5; tail = ultimas 5"),
    ("info() da filas, columnas, tipos y cuantos nulos hay",
     "describe() da estadisticas (media, percentiles 25/50/75)",
     "columns lista los nombres; index da el rango de filas",
     "info / describe",
     "info = estructura y tipos; describe = estadistica"),
  ]),
  ("INDEXAR FILAS Y COLUMNAS", [
    ("df['col'] (un string) devuelve una Series",
     "df[['a', 'b']] (una lista) devuelve un DataFrame",
     "Una columna = Series; varias columnas = DataFrame",
     "Indexar columnas",
     "un string da Series; una lista da DataFrame"),
    ("iloc localiza por POSICION numerica: df.iloc[0] es la 1ra fila",
     "loc localiza por ETIQUETA o condicion: df.loc[df['x'] == 'A']",
     "iloc piensa en numeros de fila; loc piensa en etiquetas/filtros",
     "iloc vs loc",
     "iloc va por numero de fila; loc va por etiqueta/condicion"),
  ]),
  ("FILTRAR", [
    ("df[df['category'] == 'Electronics'] deja solo esas filas",
     "Por dentro es una mascara de True/False",
     "El filtro se mete dentro de df[...]",
     "Filtro booleano",
     "df[condicion] deja solo las filas que dan True"),
    ("&amp; exige AMBAS condiciones; | basta con UNA",
     "Cada condicion va entre parentesis propios",
     "Se usan &amp; y | (NO los 'and'/'or' de Python)",
     "Combinar filtros",
     "&amp; = las dos, | = alguna; cada condicion entre parentesis"),
    (".str.startswith/.endswith filtran por texto",
     ".isin([...]) filtra por estar en una lista de valores",
     "~ delante invierte el filtro (lo que NO cumple)",
     "Filtros avanzados",
     "isin filtra por lista; ~ niega el filtro"),
  ]),
  ("ACTUALIZAR Y BORRAR", [
    ("df.loc[condicion, 'columna'] = valor localiza y cambia",
     "Primero ubicas la(s) fila(s), luego la columna a tocar",
     "df['col'] = df['col'].str.upper() cambia TODA la columna",
     "Actualizar con loc",
     "loc[condicion, col] = valor: ubica y modifica"),
    ("df.drop(39) borra la fila de ese indice",
     "dropna() quita filas con nulos; fillna(0) los rellena",
     "inplace=True modifica el original; sin el, devuelve uno nuevo",
     "Limpiar y borrar",
     "drop borra fila, dropna quita nulos, fillna los rellena"),
  ]),
  ("ANALIZAR Y GUARDAR", [
    ("value_counts() cuenta cuantas veces aparece cada valor de una columna",
     "groupby('x')['y'].sum() agrupa y resume (suma y por cada x)",
     "sort_values('col', ascending=False) ordena",
     "Resumir datos",
     "value_counts cuenta por valor; groupby agrupa y resume"),
    ("df.to_csv('archivo.csv') guarda el DataFrame en un CSV",
     "index=False evita escribir la columna de indices",
     "read_csv carga; to_csv guarda",
     "to_csv",
     "to_csv guarda; index=False omite el indice"),
  ]),
]
