# -*- coding: utf-8 -*-
# Contenido derivado de "The Complete Python Course" (Tech With Tim,
# youtube.com/watch?v=sxTmJE4k0ho): fundamentos -> POO -> intermedio -> experto.
# Misma metodologia de ejes que frontend/backend/data/flask.
NAME = "Python"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Quiero guardar datos y saber de que tipo son", [
    ("Guardar un valor con un nombre para reutilizarlo",
     "Variable: nombre = valor"),
    ("Representar un numero entero (sin decimales)",
     "int (1, -5, 0)"),
    ("Representar texto",
     "str (entre comillas: 'hola', '2')"),
    ("Representar verdadero o falso",
     "bool (True / False, con mayuscula)"),
    ("Representar un numero con decimales",
     "float (1.23)"),
    ("Recordar que '2' no es lo mismo que 2",
     "un numero entre comillas es str, no int"),
  ]),
  ("Quiero operar con los datos y pedir entrada al usuario", [
    ("Hacer las cuatro operaciones basicas",
     "+ - * /"),
    ("Elevar a una potencia",
     "** (exponente: 2**3 = 8)"),
    ("Dividir quedandome solo con la parte entera",
     "// (division entera: 7//2 = 3)"),
    ("Obtener el residuo de una division",
     "% (modulo: 7%2 = 1)"),
    ("Mostrar algo en consola",
     "print(...)"),
    ("Pedir un dato al usuario",
     "input(...) (SIEMPRE devuelve str)"),
    ("Convertir ese texto a numero para poder sumar",
     "int(x) / float(x)"),
  ]),
  ("Quiero comparar valores y tomar decisiones", [
    ("Comprobar si dos cosas son iguales",
     "== (dos signos; uno solo asigna)"),
    ("Comparar distinto, mayor o menor",
     "!=, &gt;, &lt;, &gt;=, &lt;="),
    ("Ejecutar codigo solo si una condicion es cierta",
     "if condicion:"),
    ("Dar una alternativa cuando es falsa",
     "else:"),
    ("Encadenar varias condiciones excluyentes",
     "elif"),
    ("Que Python sepa que linea pertenece al bloque",
     "indentacion (sangria tras los :)"),
  ]),
  ("Quiero combinar varias condiciones", [
    ("Exigir que se cumplan AMBAS",
     "and"),
    ("Que baste con que se cumpla UNA",
     "or"),
    ("Invertir el valor de una condicion",
     "not"),
    ("Meter una decision dentro de otra",
     "if anidado"),
  ]),
  ("Quiero repetir codigo", [
    ("Repetir un numero conocido de veces",
     "for x in range(inicio, fin, paso)"),
    ("Recorrer cada elemento de una coleccion",
     "for item in lista (iterar por item)"),
    ("Repetir MIENTRAS una condicion sea cierta",
     "while condicion:"),
    ("Salir del bucle antes de tiempo",
     "break"),
  ]),
  ("Quiero guardar muchos valores juntos", [
    ("Una coleccion ordenada y modificable",
     "list [a, b, c]"),
    ("Acceder a un elemento por su posicion",
     "lista[indice] (empieza en 0)"),
    ("Anadir un elemento al final",
     "lista.append(x)"),
    ("Cambiar un elemento existente",
     "lista[i] = nuevo"),
    ("Una coleccion que NO cambia (coordenadas, colores)",
     "tuple (a, b, c) con parentesis"),
    ("Saber cuantos elementos tiene",
     "len(coleccion)"),
  ]),
  ("Quiero cortar trozos de una lista o un texto", [
    ("Sacar un trozo de una secuencia",
     "slicing: secuencia[inicio:fin:paso]"),
    ("Recordar que el fin NO se incluye",
     "[0:5] llega hasta el indice 4"),
    ("Tomar desde el principio o hasta el final",
     "dejar el lado vacio: [:5] o [2:]"),
    ("Quitar el ultimo caracter",
     "[:-1]"),
  ]),
  ("Quiero manipular texto", [
    ("Quitar espacios (o saltos) al inicio y al final",
     ".strip()"),
    ("Pasar todo a minusculas o mayusculas",
     ".lower() / .upper()"),
    ("Partir un string en una lista por un separador",
     ".split(delimitador)"),
    ("Contar cuantas veces aparece algo",
     ".count(x)"),
    ("Encontrar la posicion de algo (o -1 si no esta)",
     ".find(x)"),
  ]),
  ("Quiero empaquetar codigo reutilizable", [
    ("Definir un bloque reutilizable",
     "def nombre(parametros):"),
    ("Devolver un resultado al que llama",
     "return"),
    ("Recibir datos al definir vs al llamar",
     "parametro (en la def) / argumento (en la llamada)"),
    ("Dar a un parametro un valor por defecto",
     "parametro opcional: param=valor"),
    ("Cambiar solo el 2do opcional",
     "hay que pasar tambien el 1ro (por orden)"),
  ]),
  ("Quiero leer y escribir archivos", [
    ("Abrir un archivo",
     "open('archivo.txt', modo)"),
    ("Leerlo sin borrar su contenido",
     "modo 'r' (read)"),
    ("Escribir borrando lo anterior",
     "modo 'w' (write: BORRA el contenido)"),
    ("Guardar los cambios al terminar",
     "archivo.close() (o usar with)"),
    ("Saltar de linea al escribir",
     "el caracter de escape \\n"),
    ("Quitar el \\n al leer cada linea",
     ".strip()"),
  ]),
  ("Quiero organizar el codigo en varios archivos", [
    ("Usar codigo de otro archivo o de una libreria",
     "import modulo"),
    ("Usar funciones matematicas ya hechas",
     "import math (math.sqrt, math.pi)"),
    ("Crear mi propio modulo",
     "otro .py en la misma carpeta + import"),
    ("Acceder a algo de dentro del modulo",
     "modulo.funcion()"),
  ]),
  ("Quiero que el programa no se caiga ante un error", [
    ("Intentar algo que puede fallar",
     "try:"),
    ("Reaccionar si falla, en vez de crashear",
     "except:"),
    ("Validar que la entrada sea un numero",
     "try: int(texto)  /  except: ..."),
  ]),
  ("Quiero saber que variables ve cada parte del codigo", [
    ("Variable visible en todo el programa",
     "variable global"),
    ("Variable que solo existe dentro de una funcion",
     "variable local"),
    ("Modificar una global desde dentro de una funcion",
     "palabra clave global"),
  ]),
  ("Quiero crear mis propios tipos de datos", [
    ("Definir el molde de un objeto",
     "class Nombre:"),
    ("Codigo que corre al crear el objeto",
     "__init__ (constructor)"),
    ("Atributo que pertenece a la instancia",
     "self.atributo"),
    ("Que representa self",
     "la instancia concreta sobre la que se llama"),
    ("Crear un objeto de esa clase",
     "obj = Clase(args)"),
  ]),
  ("Quiero reutilizar una clase dentro de otra", [
    ("Heredar atributos y metodos de otra clase",
     "class Hija(Padre):"),
    ("Llamar al constructor del padre",
     "super().__init__(...)"),
    ("Cambiar un metodo heredado",
     "sobrescribir (override): redefinirlo en la hija"),
  ]),
  ("Quiero que mis objetos respondan a + * == print() len()", [
    ("Definir que hace + entre dos objetos",
     "__add__"),
    ("Definir como se imprime el objeto",
     "__str__ / __repr__"),
    ("Definir que devuelve len(obj)",
     "__len__"),
    ("Comparar objetos con &gt; == &lt;",
     "__gt__, __eq__, __lt__..."),
    ("Como se llaman estos metodos especiales",
     "dunder / magic methods"),
  ]),
  ("Quiero metodos que no dependan de una instancia", [
    ("Metodo que recibe la clase, no la instancia",
     "@classmethod (recibe cls)"),
    ("Metodo que no recibe ni self ni la clase",
     "@staticmethod"),
    ("Variable compartida por toda la clase",
     "variable de clase (fuera de los metodos)"),
  ]),
  ("Quiero marcar que es interno y no se debe tocar", [
    ("Senalar algo como privado",
     "un guion bajo inicial: _nombre"),
    ("Recordar que Python no lo impide de verdad",
     "es solo una convencion"),
    ("Importar una clase concreta de otro archivo",
     "from modulo import Clase"),
  ]),
  ("Quiero aplicar una funcion a toda una lista sin un for", [
    ("Aplicar una funcion a CADA elemento",
     "map(funcion, lista)"),
    ("Quedarme solo con los que cumplen una condicion",
     "filter(funcion, lista)"),
    ("Definir una funcion pequena en una sola linea",
     "lambda x: expresion"),
    ("Ver el resultado como lista",
     "envolver en list(map(...))"),
  ]),
  ("Quiero estructuras de datos mas potentes", [
    ("Contar ocurrencias automaticamente",
     "Counter (del modulo collections)"),
    ("Una tupla cuyos campos tienen nombre",
     "namedtuple"),
    ("Lista rapida para anadir/quitar en ambos extremos",
     "deque"),
  ]),
  ("Quiero entender como corre mi codigo", [
    ("Traducir el codigo a algo mas cercano a la maquina",
     "compilador -&gt; bytecode"),
    ("Ejecutar ese bytecode linea por linea",
     "interprete"),
    ("Por que un metodo inexistente no falla hasta correr",
     "Python compila sintaxis y valida en runtime"),
  ]),
  ("Quiero tecnicas avanzadas de Python", [
    ("Modificar el comportamiento de una funcion sin tocar su codigo",
     "decorador (@)"),
    ("Generar valores uno a uno sin guardarlos todos en memoria",
     "generador (yield)"),
    ("Garantizar abrir/cerrar o bloquear/liberar un recurso",
     "context manager (with)"),
    ("Definir las reglas de como se crea una CLASE",
     "metaclase"),
  ]),
]

# INTEGRADOR: de las SENALES concretas (discriminadores) al concepto + tip verbalizable.
ESTACIONES = [
  ("TIPOS DE DATOS", [
    ("Es cualquier numero entero, positivo o negativo",
     "1, -5, 0 son ejemplos; NO lleva comillas ni decimales",
     "Si lo pones entre comillas deja de serlo",
     "int",
     "sin comillas y sin decimales: es un entero"),
    ("Es cualquier cosa entre comillas, simples o dobles",
     "'2' y '3.5' son texto, aunque parezcan numeros",
     "input() siempre devuelve este tipo",
     "str",
     "entre comillas = texto, aunque sea un numero"),
    ("Solo tiene dos valores posibles",
     "Se escriben True y False, con MAYUSCULA inicial",
     "Una comparacion (==, &lt;, &gt;) devuelve uno de estos",
     "bool",
     "True/False con mayuscula; nacen de una comparacion"),
  ]),
  ("OPERADORES", [
    ("** eleva a una potencia (2**3 = 8)",
     "// divide quedandose solo con el entero (7//2 = 3)",
     "% da el residuo de la division (7%2 = 1)",
     "Operadores **, //, %",
     "doble asterisco eleva, doble barra trunca, porcentaje da residuo"),
    ("Un solo signo igual ASIGNA un valor (x = 4)",
     "Dos signos COMPARAN si son iguales (x == 4)",
     "Usar uno donde va el otro es el error mas clasico",
     "= vs ==",
     "uno asigna, dos comparan"),
    ("input() pausa y deja al usuario escribir",
     "Lo que devuelve SIEMPRE es str, aunque escriba un numero",
     "Para sumar hay que envolverlo en int() o float()",
     "input + conversion",
     "input siempre da texto; int() lo vuelve numero"),
  ]),
  ("DECISIONES", [
    ("if revisa la primera condicion",
     "elif revisa otra solo si las anteriores fueron falsas",
     "else es el caso por defecto, sin condicion; solo puede haber uno",
     "if / elif / else",
     "if abre, elif encadena, else recoge el resto"),
    ("Python no usa llaves para los bloques",
     "El codigo a ejecutar va sangrado bajo los :",
     "Una mala indentacion cambia o rompe la logica",
     "Indentacion",
     "la sangria es la que define el bloque en Python"),
    ("and exige que AMBAS condiciones sean verdaderas",
     "or basta con que UNA sea verdadera",
     "not invierte el valor (True se vuelve False)",
     "and / or / not",
     "and = las dos; or = al menos una; not = al reves"),
  ]),
  ("BUCLES", [
    ("for x in range(n) repite un numero conocido de veces",
     "for item in lista recorre cada elemento (por item)",
     "En range(inicio, fin, paso) el fin NO se incluye",
     "for",
     "range itera por indice; in lista itera por item"),
    ("Se usa cuando NO sabes cuantas veces vas a repetir",
     "Repite mientras una condicion siga siendo cierta",
     "break te saca del bucle antes de tiempo",
     "while",
     "for = veces conocidas; while = hasta que se cumpla algo"),
  ]),
  ("LISTAS Y TUPLAS", [
    ("list usa corchetes [] y SI se puede modificar",
     "tuple usa parentesis () y NO se puede modificar",
     "tuple para datos fijos: coordenadas, colores RGB",
     "list vs tuple",
     "corchetes mutan; parentesis no"),
    ("El primer elemento es el indice 0, no 1",
     "lista[1] devuelve el SEGUNDO elemento",
     "len() dice cuantos hay en total",
     "Indexacion base 0",
     "se cuenta desde 0: el 2do elemento es [1]"),
    ("append(x) agrega al FINAL de la lista",
     "lista[i] = x reemplaza el elemento en esa posicion",
     "para reemplazar necesitas un indice ya existente",
     "append vs asignar indice",
     "append agrega al final; [i]= reemplaza en su sitio"),
    ("[inicio:fin:paso] saca un trozo de lista o string",
     "El fin NO se incluye, igual que en range",
     "Dejar un lado vacio = desde el principio / hasta el final",
     "Slicing",
     "rebana [inicio:fin:paso]; el fin queda fuera"),
  ]),
  ("METODOS DE STRING", [
    (".strip() quita espacios (o \\n) de los extremos",
     ".lower()/.upper() cambian entre minusculas y mayusculas",
     "No modifican el original: devuelven un string nuevo",
     "strip / lower / upper",
     "strip recorta extremos; lower/upper cambian la caja"),
    (".split(delim) parte el string en una LISTA",
     ".find(x) da la posicion (indice), o -1 si no esta",
     ".count(x) da cuantas veces aparece",
     "split / find / count",
     "split trocea, find ubica (-1 si falta), count cuenta"),
  ]),
  ("FUNCIONES", [
    ("El parametro esta en la definicion: def f(x)",
     "El argumento es el valor real al llamar: f(5)",
     "return devuelve un resultado; print solo lo muestra",
     "Parametro vs argumento",
     "parametro se define, argumento se pasa"),
    ("param=valor le da un valor por defecto",
     "Si no lo pasas usa el default; si lo pasas lo sobrescribe",
     "Para cambiar el 2do opcional debes dar tambien el 1ro (por orden)",
     "Parametro opcional",
     "param=valor: opcional; al omitir, manda el orden"),
  ]),
  ("ARCHIVOS", [
    ("open(archivo, 'r') lee sin borrar",
     "open(archivo, 'w') BORRA todo y escribe de cero",
     "Hay que close() (o usar with) para guardar los cambios",
     "Modos de archivo r / w",
     "r lee, w borra y reescribe; cierra siempre"),
    ("\\n es un caracter de escape: un salto de linea",
     "Al leer lineas viene pegado al final de cada una",
     ".strip() lo quita igual que a los espacios",
     "El escape \\n",
     "\\n salta de linea; strip lo limpia al leer"),
  ]),
  ("MODULOS Y ERRORES", [
    ("import trae funciones/clases de otro archivo o libreria",
     "math es built-in; pygame hay que instalarlo aparte",
     "Se usa con punto: math.sqrt, math.pi, modulo.cosa",
     "import",
     "import enchufa otro archivo; lo usas con el punto"),
    ("try: envuelve el codigo que puede fallar",
     "except: corre si hubo error, en vez de crashear",
     "Caso tipico: try int(texto) para validar la entrada",
     "try / except",
     "try intenta, except atrapa el fallo sin caerse"),
  ]),
  ("AMBITO DE VARIABLES", [
    ("Una variable creada DENTRO de una funcion es local",
     "Fuera no se ve: da NameError si la usas afuera",
     "Para modificar una global desde dentro usas la palabra global",
     "Global vs local",
     "lo de dentro es local; 'global' deja tocar la de fuera"),
  ]),
  ("CLASES (POO)", [
    ("class define el molde; __init__ corre al crear el objeto",
     "self es la instancia concreta sobre la que se llama",
     "self.x = x crea un atributo propio de esa instancia",
     "class / __init__ / self",
     "class es molde, __init__ arranca, self es la instancia"),
    ("Una funcion se llama sola: f(5)",
     "Un metodo se llama sobre un objeto: obj.metodo()",
     "El metodo recibe self automaticamente",
     "Metodo vs funcion",
     "funcion va sola; metodo va sobre un objeto (con self)"),
    ("class Hija(Padre) hereda atributos y metodos del padre",
     "super().__init__() llama al constructor del padre",
     "Redefinir un metodo en la hija lo sobrescribe (override)",
     "Herencia",
     "Hija(Padre) hereda; super() reusa; redefinir = override"),
  ]),
  ("METODOS ESPECIALES Y DE CLASE", [
    ("Llevan doble guion bajo: __add__, __str__, __len__",
     "Definen que hace +, print() o len() sobre TUS objetos",
     "Python los llama solo cuando usas ese simbolo o funcion",
     "Dunder / magic methods",
     "los __x__ enganchan +, print y len a tus objetos"),
    ("@classmethod recibe la clase (cls) y ve variables de clase",
     "@staticmethod no recibe ni self ni cls: es funcion organizada dentro",
     "Ambos se pueden llamar con el nombre de la clase, sin instancia",
     "classmethod vs staticmethod",
     "classmethod ve la clase (cls); staticmethod no ve nada de ella"),
    ("Se define arriba, fuera de los metodos",
     "Es la MISMA para todas las instancias",
     "Se accede con el nombre de la clase, sin objeto",
     "Variable de clase",
     "vive en la clase, compartida por todas las instancias"),
    ("Un guion bajo inicial marca algo como 'privado'",
     "Es solo CONVENCION: Python no lo impide de verdad",
     "Te dice 'no lo toques', no te lo prohibe",
     "Privado en Python (_nombre)",
     "el _ pide no tocar; no es una barrera real"),
  ]),
  ("ORDEN SUPERIOR", [
    ("map aplica una funcion a CADA elemento de la lista",
     "filter se queda solo con los que dan True",
     "Ambos necesitan list(...) para verse como lista",
     "map vs filter",
     "map transforma todos; filter selecciona algunos"),
    ("Es una funcion anonima en una linea: lambda x: x+5",
     "Solo una expresion, sin def y sin nombre",
     "Ideal dentro de map/filter sin crear funcion aparte",
     "lambda",
     "lambda = funcion expres de una linea, sin nombre"),
    ("Counter cuenta ocurrencias y tiene most_common()",
     "namedtuple es una tupla con campos por nombre (.x)",
     "deque anade/quita rapido en ambos extremos (appendleft, rotate)",
     "Modulo collections",
     "Counter cuenta, namedtuple nombra campos, deque vuela en los extremos"),
  ]),
  ("COMO CORRE PYTHON", [
    ("El compilador traduce tu codigo a bytecode (revisa la sintaxis)",
     "El interprete ejecuta ese bytecode linea por linea",
     "Por eso un metodo inexistente NO falla hasta runtime",
     "Ejecucion de Python",
     "compila a bytecode y lo interpreta en vivo; valida al correr"),
  ]),
  ("AVANZADO", [
    ("Se pone con @ encima de una funcion",
     "Envuelve la funcion para cambiar su comportamiento SIN tocar su codigo",
     "Por dentro hace: func = decorador(func)",
     "Decorador",
     "@deco envuelve la funcion y la modifica sin editarla"),
    ("Usa yield en lugar de return",
     "yield PAUSA la funcion y entrega un valor; no la termina",
     "Produce valores uno a uno sin guardarlos todos en memoria",
     "Generador",
     "yield pausa y entrega; ahorra memoria dando de a uno"),
    ("Se usa con la palabra with",
     "Garantiza una accion de salida (cerrar/liberar) pase lo que pase",
     "Implementa __enter__ y __exit__ (o @contextmanager + yield)",
     "Context manager",
     "with asegura el cierre aunque haya una excepcion"),
    ("Una clase es un objeto, creado por type",
     "Define las reglas de como se crea una CLASE (no un objeto normal)",
     "Engancha en __new__ para modificar la construccion de clases",
     "Metaclase",
     "la metaclase fabrica clases como la clase fabrica objetos"),
  ]),
]
