# -*- coding: utf-8 -*-
# CAPA 1 de 3 del sistema de meta-analisis: Disenos y evidencia.
# Fuente: Cochrane Handbook for Systematic Reviews of Interventions v6.5
# (caps. 2-3 diseno de la pregunta, 8 riesgo de sesgo, 14 GRADE, 24 no-aleatorizados).
# Misma metodologia de ejes que el resto del repo.
NAME = "Research - Capa 1 Disenos"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Tengo un paper delante y no se que tipo de estudio es", [
    ("Asignan la intervencion AL AZAR y siguen a los dos grupos",
     "ECA / RCT (ensayo clinico aleatorizado)"),
    ("Aleatorizan grupos enteros (colegios, consultorios), no personas",
     "ECA por conglomerados (cluster) - las personas del mismo grupo se parecen"),
    ("Cada paciente recibe las dos intervenciones en dos periodos",
     "ECA cruzado (cross-over) - cada paciente es su propio control"),
    ("Parten de la EXPOSICION y siguen hacia adelante quien enferma",
     "Cohorte (prospectiva o retrospectiva)"),
    ("Parten del DESENLACE y miran hacia atras quien estuvo expuesto",
     "Caso-control"),
    ("Miden exposicion y desenlace a la vez, en un solo momento",
     "Transversal (cross-sectional) - da prevalencia, no incidencia"),
    ("Describen pacientes sin grupo de comparacion",
     "Serie de casos - no permite estimar efecto"),
  ]),
  ("Necesito saber que puedo pedirle a cada diseno", [
    ("Que diseno puede establecer causalidad con menos supuestos",
     "ECA: la aleatorizacion equilibra confusores conocidos Y desconocidos"),
    ("Que diseno sirve para desenlaces MUY raros",
     "Caso-control: recluta por el desenlace, asi consigue casos suficientes"),
    ("Que diseno sirve para exposiciones raras o para varios desenlaces a la vez",
     "Cohorte"),
    ("Que diseno mide cuanta gente lo tiene AHORA",
     "Transversal (prevalencia)"),
    ("Que diseno mide cuantos casos NUEVOS aparecen por unidad de tiempo",
     "Cohorte (incidencia)"),
  ]),
  ("Quiero saber que medida de efecto NACE de cada diseno", [
    ("De un caso-control",
     "solo OR - no conoce el denominador de riesgo, no puede dar RR"),
    ("De un ECA o cohorte con desenlace si/no",
     "RR, OR o RD (y de la RD sale el NNT)"),
    ("De un estudio con seguimiento y censura (supervivencia)",
     "HR (hazard ratio)"),
    ("De un desenlace continuo en la misma escala en todos los estudios",
     "MD (diferencia de medias)"),
    ("De un desenlace continuo con escalas distintas entre estudios",
     "SMD (Hedges g)"),
  ]),
  ("Voy a definir la pregunta de mi meta-analisis", [
    ("El marco que estructura la pregunta",
     "PICO: Poblacion, Intervencion, Comparador, Outcome"),
    ("La pieza que se olvida y hunde el proyecto",
     "el Comparador: 'placebo' y 'tratamiento habitual' NO son lo mismo"),
    ("Cuantos desenlaces principales se declaran",
     "UNO primario; el resto son secundarios y se reportan como tales"),
    ("Donde se registra la pregunta antes de empezar",
     "PROSPERO (o OSF) - antes del screening, no despues"),
    ("Por que se registra antes",
     "para que no puedas cambiar el outcome despues de ver los resultados"),
    ("Como se llama cambiarlo despues",
     "outcome switching - es sesgo de reporte, no un ajuste"),
  ]),
  ("Tengo que decidir a quien dejo entrar al meta-analisis", [
    ("Donde se escriben los criterios de inclusion y exclusion",
     "en el protocolo, ANTES de buscar"),
    ("Que se hace con cada estudio excluido en full-text",
     "se registra con la razon escrita (PRISMA lo exige)"),
    ("Cuando hay que documentar la razon",
     "en full-text siempre; en titulo/abstract basta el conteo"),
    ("Cuantos revisores deberian cribar",
     "dos independientes, con un tercero que resuelve desacuerdos"),
    ("Que se hace si dos papers reportan la misma cohorte",
     "es UN estudio, no dos - se elige el reporte mas completo"),
  ]),
  ("Tengo que evaluar si me creo cada estudio (riesgo de sesgo)", [
    ("Herramienta para ECA",
     "RoB 2 (Cochrane risk-of-bias tool version 2)"),
    ("Herramienta para estudios NO aleatorizados de intervencion",
     "ROBINS-I"),
    ("Herramienta para cohortes y caso-control en revisiones no-Cochrane",
     "Newcastle-Ottawa Scale (NOS)"),
    ("Herramienta para estudios de pruebas diagnosticas",
     "QUADAS-2"),
    ("Sobre que se evalua el riesgo de sesgo",
     "sobre CADA desenlace, no sobre el estudio entero"),
  ]),
  ("Necesito los cinco dominios de RoB 2 de memoria", [
    ("Dominio 1",
     "sesgo derivado del proceso de aleatorizacion"),
    ("Dominio 2",
     "desviaciones de la intervencion prevista (ITT vs per-protocol)"),
    ("Dominio 3",
     "datos de desenlace faltantes (perdidas de seguimiento)"),
    ("Dominio 4",
     "medicion del desenlace (cegamiento del evaluador)"),
    ("Dominio 5",
     "seleccion del resultado reportado (protocolo vs publicado)"),
    ("Los tres juicios posibles",
     "bajo riesgo / algunas preocupaciones / alto riesgo"),
    ("Como se obtiene el juicio global",
     "el peor dominio manda: un solo dominio alto = global alto"),
  ]),
  ("Se me confunden los tipos de sesgo", [
    ("Los grupos ya eran distintos antes de empezar",
     "sesgo de seleccion - lo previene la aleatorizacion + ocultacion de asignacion"),
    ("Los grupos reciben cuidados distintos ademas de la intervencion",
     "sesgo de realizacion (performance) - lo previene el cegamiento de pacientes y personal"),
    ("Quien mide el desenlace sabe en que grupo esta el paciente",
     "sesgo de deteccion - lo previene el cegamiento del evaluador"),
    ("Se pierden mas pacientes en un brazo que en otro",
     "sesgo de desgaste (atricion) - lo mitiga el analisis por intencion de tratar"),
    ("Solo publican los desenlaces que salieron bonitos",
     "sesgo de reporte selectivo - se detecta comparando protocolo y publicacion"),
  ]),
  ("Tengo que decir cuanta confianza merece el resultado global", [
    ("El sistema que se usa",
     "GRADE - se aplica POR desenlace, no al meta-analisis entero"),
    ("Los cuatro niveles de certeza",
     "alta / moderada / baja / muy baja"),
    ("Donde arranca un cuerpo de ECAs",
     "en certeza ALTA, y va bajando"),
    ("Donde arranca un cuerpo de estudios observacionales",
     "en certeza BAJA, y puede subir"),
    ("Las cinco razones para BAJAR",
     "riesgo de sesgo, inconsistencia, evidencia indirecta, imprecision, sesgo de publicacion"),
    ("Las tres razones para SUBIR (solo observacionales)",
     "efecto grande, gradiente dosis-respuesta, confusores que irian en contra"),
    ("La tabla final que resume todo",
     "Summary of Findings (SoF)"),
  ]),
]

# INTEGRADOR: de las SENALES al concepto + como verbalizarlo.
ESTACIONES = [
  ("PUERTA DE ENTRADA DEL ESTUDIO", [
    ("El investigador recluta gente POR tener ya el desenlace",
     "Busca hacia atras quien estuvo expuesto",
     "No sabe cuanta gente sana estaba expuesta en la poblacion",
     "Caso-control",
     "el caso-control entra por la puerta del desenlace, por eso solo puede hablar de odds"),
    ("El investigador recluta por la EXPOSICION y espera",
     "Conoce el denominador de cada brazo",
     "Puede calcular incidencia en expuestos y no expuestos",
     "Cohorte",
     "si conoces el denominador, puedes hablar de riesgo; si no, solo de odds"),
    ("El investigador ASIGNA la intervencion, no la observa",
     "La asignacion es al azar",
     "Equilibra confusores conocidos y tambien los desconocidos",
     "Ensayo clinico aleatorizado (ECA)",
     "aleatorizar es lo unico que equilibra lo que ni siquiera sabes que existe"),
    ("Exposicion y desenlace se miden en el mismo instante",
     "No hay seguimiento en el tiempo",
     "No se puede saber que ocurrio primero",
     "Estudio transversal",
     "una foto no distingue causa de consecuencia; para eso hace falta una pelicula"),
  ]),
  ("VARIANTES DEL ECA", [
    ("Se aleatorizan colegios, consultorios o barrios enteros",
     "Las personas dentro de cada grupo se parecen entre si",
     "Si se ignora eso, el IC sale falsamente estrecho",
     "ECA por conglomerados (cluster)",
     "si aleatorizas grupos, la unidad de analisis es el grupo, no la persona"),
    ("Cada paciente pasa por las dos ramas en dos periodos",
     "Cada paciente es su propio control",
     "Hay riesgo de arrastre del primer periodo (carryover)",
     "ECA cruzado (cross-over)",
     "el cross-over gana potencia pero necesita un periodo de lavado entre fases"),
    ("Se analiza a la gente en el grupo al que fue ASIGNADA",
     "Aunque se haya cambiado de rama o abandonado",
     "Conserva el equilibrio que dio la aleatorizacion",
     "Analisis por intencion de tratar (ITT)",
     "analizar por lo que hicieron y no por lo asignado rompe la aleatorizacion"),
  ]),
  ("LA PREGUNTA", [
    ("Estructura la pregunta en cuatro piezas",
     "Sin ella los criterios de inclusion quedan ambiguos",
     "Es lo primero que se escribe en el protocolo",
     "PICO",
     "P de a quien, I de que le haces, C contra que lo comparas, O que mides"),
    ("Es la pieza del PICO que mas se descuida",
     "Placebo y tratamiento habitual dan resultados distintos",
     "Si es heterogeneo, la heterogeneidad estadistica se dispara",
     "El Comparador",
     "un efecto siempre es contra algo: si el 'algo' cambia, el efecto no es el mismo"),
    ("Se declara UNO solo antes de empezar",
     "Determina el calculo de potencia y el analisis principal",
     "Cambiarlo tras ver los datos es sesgo de reporte",
     "Desenlace primario",
     "el desenlace primario se elige a ciegas o no se eligio, se escogio"),
    ("Registro publico antes de iniciar el cribado",
     "Deja constancia con fecha de lo que ibas a hacer",
     "Los revisores lo comparan con lo publicado",
     "PROSPERO",
     "registrar antes convierte tu promesa en evidencia verificable"),
  ]),
  ("HERRAMIENTAS DE RIESGO DE SESGO", [
    ("Cinco dominios, tres juicios posibles",
     "Solo para ensayos aleatorizados",
     "El juicio global lo manda el peor dominio",
     "RoB 2",
     "en RoB 2 no se promedian dominios: un dominio en alto tine todo el estudio"),
    ("Siete dominios, incluye confusion residual",
     "Para estudios no aleatorizados de intervencion",
     "Compara el estudio real contra el ensayo ideal (target trial)",
     "ROBINS-I",
     "ROBINS-I pregunta que tan lejos estas del ensayo que habrias querido hacer"),
    ("Sistema de estrellas por seleccion, comparabilidad y desenlace",
     "Para cohortes y caso-control",
     "Frecuente fuera de Cochrane, criticada por su puntaje sumatorio",
     "Newcastle-Ottawa (NOS)",
     "sumar estrellas mezcla dominios que no pesan igual: reporta el detalle, no solo el total"),
    ("Se aplica a cada desenlace por separado",
     "Un mismo estudio puede ser bajo riesgo para mortalidad y alto para dolor",
     "Porque el cegamiento importa distinto segun lo subjetivo del desenlace",
     "El riesgo de sesgo es por desenlace",
     "el sesgo no vive en el paper, vive en la pareja estudio-desenlace"),
  ]),
  ("FAMILIAS DE SESGO", [
    ("Los grupos ya diferian antes de la intervencion",
     "Se previene aleatorizando",
     "Y ocultando la secuencia a quien recluta",
     "Sesgo de seleccion",
     "si quien recluta puede adivinar la siguiente asignacion, la aleatorizacion ya no protege"),
    ("Quien mide el desenlace sabe en que rama esta el paciente",
     "Grave si el desenlace es subjetivo (dolor, escala clinica)",
     "Casi irrelevante si el desenlace es mortalidad",
     "Sesgo de deteccion",
     "cuanto mas subjetivo el desenlace, mas caro sale no cegar al evaluador"),
    ("Se pierde seguimiento de forma desigual entre ramas",
     "Los que abandonan suelen diferir de los que siguen",
     "Se mitiga con ITT y analisis de sensibilidad",
     "Sesgo de desgaste (atricion)",
     "la gente no se pierde al azar: se pierde por razones que suelen ser el desenlace"),
    ("El protocolo prometia seis desenlaces y el paper reporta tres",
     "Justo los tres significativos",
     "Se detecta comparando registro y publicacion",
     "Sesgo de reporte selectivo",
     "lo que falta en un paper informa tanto como lo que aparece"),
  ]),
  ("GRADE", [
    ("Se aplica por desenlace, no al meta-analisis entero",
     "Da cuatro niveles: alta, moderada, baja, muy baja",
     "Califica la confianza en la estimacion, no su magnitud",
     "GRADE",
     "GRADE no dice si el tratamiento sirve, dice cuanto puedes fiarte de que sirve"),
    ("Un cuerpo de ECAs empieza aqui",
     "Un cuerpo de observacionales empieza en baja",
     "Desde ahi se baja por cinco razones",
     "Certeza alta",
     "el diseno fija tu punto de partida; los dominios deciden cuanto te mueves"),
    ("I2 muy alto sin explicacion por subgrupos",
     "Los estudios apuntan en direcciones opuestas",
     "Es una de las cinco razones para bajar",
     "Inconsistencia",
     "si los estudios no se ponen de acuerdo, el promedio de todos vale menos"),
    ("El IC cruza el umbral de decision clinica",
     "O el tamano de muestra total es pequeno",
     "Otra de las cinco razones para bajar",
     "Imprecision",
     "un IC que abarca 'dana' y 'cura' no es un resultado, es una pregunta abierta"),
    ("Tu poblacion, intervencion o desenlace no son los de la pregunta",
     "Usaste un desenlace subrogado en vez del clinico",
     "Otra de las cinco razones para bajar",
     "Evidencia indirecta",
     "bajar el colesterol no es lo mismo que evitar infartos: eso es indireccion"),
  ]),
]
