# -*- coding: utf-8 -*-
# CAPA 2 de 3 del sistema de meta-analisis: Estadistica de la sintesis.
# Fuente: Harrer, Cuijpers, Furukawa & Ebert, "Doing Meta-Analysis with R"
# (caps. 3 efectos, 4 pooling, 5 heterogeneidad, 7 subgrupos, 8 meta-regresion,
# 9 sesgo de publicacion, 17 conversion) + Cochrane Handbook v6.5 caps. 10 y 13.
NAME = "Research - Capa 2 Estadistica"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Tengo un desenlace binario (paso / no paso) y una tabla 2x2", [
    ("Los estudios son ECA o cohortes y conozco el denominador",
     "RR (riesgo relativo) - el mas interpretable clinicamente"),
    ("Los estudios son caso-control",
     "OR - es la unica que ese diseno puede estimar"),
    ("Quiero el impacto absoluto, no el relativo",
     "RD (diferencia de riesgos); NNT = 1 / RD"),
    ("Por que no se promedian los ratios tal cual",
     "son asimetricos alrededor de 1: se agrupan en escala log y se exponencia al final"),
    ("Que pasa si un brazo tiene CERO eventos",
     "el log no existe: se aplica correccion de continuidad (+0.5) o se usa Peto/MH"),
  ]),
  ("Tengo un desenlace continuo (una escala, un numero)", [
    ("Todos los estudios usan la MISMA escala",
     "MD (diferencia de medias) - conserva las unidades originales"),
    ("Cada estudio usa una escala DISTINTA",
     "SMD - se divide por la desviacion estandar combinada"),
    ("Corregir el sesgo de la SMD con muestras pequenas",
     "Hedges g (es la Cohen d corregida)"),
    ("Que tres datos necesito de cada brazo",
     "n, media y desviacion estandar"),
    ("Solo tengo mediana y rango intercuartilico",
     "hay formulas de conversion (Wan, Luo) - Harrer cap. 17"),
  ]),
  ("El desenlace es tiempo hasta el evento", [
    ("La medida que respeta la censura",
     "HR (hazard ratio)"),
    ("Que necesito extraer del paper",
     "log(HR) y su error estandar, o el HR con su IC95%"),
    ("Como saco el SE desde un IC95% en escala log",
     "SE = (log(IC_sup) - log(IC_inf)) / 3.92"),
    ("Por que esa via es peor que tener datos crudos",
     "pierde informacion y depende del redondeo del paper"),
  ]),
  ("Quiero entender de donde sale el efecto combinado", [
    ("La idea central del pooling",
     "es un promedio PONDERADO de los efectos, no un promedio simple"),
    ("Que le da peso a un estudio",
     "el inverso de su varianza: menos incertidumbre, mas peso"),
    ("Que hace que un estudio tenga poca varianza",
     "muestra grande y muchos eventos"),
    ("El metodo general de ponderacion",
     "inverse variance (varianza inversa)"),
    ("El metodo preferido para binarios con pocos eventos",
     "Mantel-Haenszel (MH) - mas estable que varianza inversa"),
    ("El metodo para eventos MUY raros y grupos balanceados",
     "Peto"),
  ]),
  ("Tengo que elegir entre efectos fijos y aleatorios", [
    ("Que asume el modelo de efectos FIJOS (common effect)",
     "existe UN solo efecto verdadero; toda diferencia es error de muestreo"),
    ("Que asume el modelo de efectos ALEATORIOS",
     "hay una DISTRIBUCION de efectos verdaderos; se estima su media"),
    ("Cual es el default razonable en investigacion clinica",
     "aleatorios: poblaciones, dosis y contextos siempre difieren"),
    ("Que le pasa a los pesos con efectos aleatorios",
     "se aplanan: los estudios pequenos pesan relativamente mas"),
    ("Que le pasa al IC con efectos aleatorios",
     "se ensancha, porque incorpora la varianza entre estudios"),
  ]),
  ("Necesito decidir como estimar tau cuadrado", [
    ("Que es tau cuadrado",
     "la varianza ENTRE estudios (la dispersion de los efectos verdaderos)"),
    ("El estimador clasico, rapido y con sesgo",
     "DerSimonian-Laird (DL)"),
    ("El estimador recomendado por defecto hoy",
     "REML (maxima verosimilitud restringida)"),
    ("El estimador robusto recomendado para binarios",
     "Paule-Mandel (PM)"),
    ("El ajuste que arregla los IC cuando k es pequeno",
     "Hartung-Knapp-Sidik-Jonkman (HKSJ)"),
    ("Por que HKSJ importa tanto en meta-analisis medicos",
     "casi siempre tienes 5-15 estudios y sin el los IC salen falsamente estrechos"),
  ]),
  ("Los estudios no dicen lo mismo y tengo que explicarlo", [
    ("Los estudios reclutan poblaciones o dosis distintas",
     "heterogeneidad CLINICA"),
    ("Los estudios tienen distinto riesgo de sesgo o seguimiento",
     "heterogeneidad METODOLOGICA"),
    ("La variacion observada supera la esperable por azar",
     "heterogeneidad ESTADISTICA (la que miden Q, I&sup2; y &tau;&sup2;)"),
    ("El orden correcto de razonamiento",
     "primero se explica clinica y metodologicamente; el numero solo confirma"),
  ]),
  ("Quiero leer bien los numeros de heterogeneidad", [
    ("El test clasico de heterogeneidad",
     "Q de Cochran - con k pequeno tiene poca potencia, un p alto no prueba homogeneidad"),
    ("Que mide I&sup2; exactamente",
     "el PORCENTAJE de la variabilidad total que se debe a heterogeneidad y no al azar"),
    ("Por que I&sup2; no es una magnitud absoluta",
     "sube solo con estudios mas precisos aunque los efectos no cambien"),
    ("Que mide &tau;&sup2; en cambio",
     "la dispersion absoluta de los efectos, en las unidades del efecto"),
    ("Los cortes orientativos de Cochrane para I&sup2;",
     "0-40 poco importante, 30-60 moderada, 50-90 sustancial, 75-100 considerable"),
    ("El numero que de verdad hay que reportar",
     "el intervalo de PREDICCION: donde caeria el efecto de un estudio futuro"),
  ]),
  ("Tengo heterogeneidad alta y hay que investigarla", [
    ("Comparar el efecto entre grupos definidos de antemano",
     "analisis de subgrupos - se juzga por el TEST DE INTERACCION, no por si cada subgrupo es significativo"),
    ("Cuantos estudios pide Cochrane por subgrupo, como minimo",
     "unos 10 estudios por covariable para que el analisis valga algo"),
    ("Explicar el efecto con una variable continua (dosis, ano, edad media)",
     "meta-regresion"),
    ("El peligro de comparar entre estudios en vez de dentro",
     "falacia ecologica y confusion agregada"),
    ("Ver como cambia el resultado quitando un estudio cada vez",
     "leave-one-out (analisis de influencia)"),
    ("Ver que estudio contribuye mas a la Q",
     "grafico de Baujat"),
    ("Regla dura sobre los subgrupos",
     "se preespecifican en el protocolo; si salen despues son generadores de hipotesis"),
  ]),
  ("Sospecho que falta evidencia sin publicar", [
    ("El grafico que lo explora",
     "funnel plot: efecto en X contra precision en Y"),
    ("Que forma tiene si no hay problema",
     "un embudo simetrico: los estudios pequenos se dispersan a ambos lados"),
    ("El test formal de asimetria para desenlaces continuos",
     "test de Egger (regresion)"),
    ("El test recomendado para desenlaces binarios",
     "test de Peters (Egger da falsos positivos con OR)"),
    ("Cuantos estudios hacen falta para poder testear",
     "k &ge; 10; con menos el test no tiene potencia"),
    ("El metodo que simula los estudios que faltarian",
     "trim-and-fill - es un analisis de sensibilidad, no una correccion definitiva"),
    ("Por que asimetria NO es igual a sesgo de publicacion",
     "tambien la causan heterogeneidad real, mala calidad de estudios pequenos o azar"),
  ]),
]

# INTEGRADOR: de las SENALES al concepto + como verbalizarlo.
ESTACIONES = [
  ("MEDIDAS BINARIAS", [
    ("Sale de un diseno que recluta por el desenlace",
     "No hay denominador de riesgo disponible",
     "Se agrupa en escala logaritmica",
     "OR (odds ratio)",
     "el caso-control entra por la puerta del desenlace, asi que solo puede hablar de odds"),
    ("Necesita conocer cuantos habia en cada brazo",
     "Sale de un ECA o de una cohorte",
     "Es la que el clinico entiende sin traduccion",
     "RR (riesgo relativo)",
     "si conoces el denominador puedes hablar de riesgo; si no, solo de odds"),
    ("Es una resta, no un cociente",
     "Conserva la escala absoluta del problema",
     "Su inverso da el numero necesario a tratar",
     "RD (diferencia de riesgos)",
     "el RR dice cuanto cambia el riesgo; la RD dice a cuanta gente le cambia"),
    ("Un brazo tiene cero eventos",
     "El logaritmo de cero no existe",
     "Se suma 0.5 a cada celda o se usa un metodo que lo tolera",
     "Correccion de continuidad",
     "una celda vacia no es un efecto infinito, es falta de informacion"),
  ]),
  ("MEDIDAS CONTINUAS", [
    ("Todos los estudios midieron con el mismo instrumento",
     "Se pueden restar las medias directamente",
     "El resultado sale en las unidades clinicas originales",
     "MD (diferencia de medias)",
     "si la regla de medir es la misma, resta y ya: no ganas nada estandarizando"),
    ("Un estudio usa Hamilton y otro usa Beck",
     "Restar medias directamente no significa nada",
     "Se divide por la desviacion estandar combinada",
     "SMD",
     "cuando cada estudio trae su propia regla de medir, dejas de comparar centimetros y comparas desviaciones estandar"),
    ("Es la SMD con un factor de correccion",
     "Corrige el sesgo al alza con muestras pequenas",
     "Es la version que se reporta por defecto",
     "Hedges g",
     "Cohen d exagera cuando hay pocos pacientes; Hedges g le baja los humos"),
  ]),
  ("EL PESO", [
    ("Es el inverso de la varianza del estudio",
     "Crece con la muestra y con el numero de eventos",
     "Decide cuanto manda cada estudio en el diamante final",
     "Ponderacion por varianza inversa",
     "en un meta-analisis no vota cada estudio, vota cada unidad de certeza"),
    ("Trabaja directo sobre las celdas de la tabla 2x2",
     "Es mas estable cuando los eventos son escasos",
     "Es el metodo por defecto para binarios en el paquete meta",
     "Mantel-Haenszel",
     "con pocos eventos la varianza inversa se vuelve inestable; MH aguanta mejor"),
    ("Pensado para eventos muy raros",
     "Requiere grupos de tamano parecido",
     "Puede sesgar si el efecto es grande",
     "Metodo de Peto",
     "Peto brilla justo donde los demas fallan: eventos rarisimos y brazos equilibrados"),
  ]),
  ("LOS DOS MODELOS", [
    ("Asume que existe un unico efecto verdadero",
     "Toda la diferencia observada es error de muestreo",
     "Da intervalos de confianza mas estrechos",
     "Efectos fijos (common effect)",
     "el modelo fijo cree que todos los estudios miden la misma cosa con distinta punteria"),
    ("Asume una distribucion de efectos verdaderos",
     "Anade la varianza entre estudios al calculo",
     "Aplana los pesos y ensancha el intervalo",
     "Efectos aleatorios",
     "el modelo aleatorio no estima EL efecto, estima el promedio de una familia de efectos"),
    ("Es la varianza ENTRE estudios",
     "Se expresa en las unidades del efecto",
     "Es el ingrediente del intervalo de prediccion",
     "&tau;&sup2; (tau cuadrado)",
     "tau cuadrado es lo ancha que es la familia de efectos, no lo mal que mides"),
    ("Corrige los intervalos cuando hay pocos estudios",
     "Usa una distribucion t en vez de la normal",
     "Casi obligatorio con k entre 5 y 15",
     "Ajuste Hartung-Knapp",
     "con pocos estudios el IC clasico miente por estrecho; Hartung-Knapp lo obliga a ser honesto"),
  ]),
  ("HETEROGENEIDAD", [
    ("Es un porcentaje, no una cantidad",
     "Mide que fraccion de la variacion no es azar",
     "Sube si los estudios son mas precisos, aunque los efectos no cambien",
     "I&sup2;",
     "I cuadrado dice que proporcion del ruido es senal, no cuanta senal hay"),
    ("Es un test, no una medida de magnitud",
     "Con pocos estudios casi nunca sale significativo",
     "Un p no significativo NO demuestra homogeneidad",
     "Q de Cochran",
     "que Q no detecte heterogeneidad suele significar que no tenias potencia, no que no la haya"),
    ("Usa tau cuadrado ademas del error del promedio",
     "Dice donde caeria el efecto de un estudio NUEVO",
     "Suele ser mucho mas ancho que el IC del efecto combinado",
     "Intervalo de prediccion",
     "el IC habla del promedio; el intervalo de prediccion habla del proximo paciente real"),
    ("Los estudios difieren en poblacion, dosis o contexto",
     "Se detecta leyendo las tablas 1 de los papers, no calculando",
     "Es la que hay que explicar antes de mirar ningun indice",
     "Heterogeneidad clinica",
     "el numero te avisa de que hay un problema; la tabla 1 te dice cual es"),
  ]),
  ("EXPLORAR LA HETEROGENEIDAD", [
    ("Compara el efecto entre grupos definidos de antemano",
     "No se juzga por si cada grupo es significativo por separado",
     "Se juzga por el test de interaccion entre grupos",
     "Analisis de subgrupos",
     "que un subgrupo salga significativo y el otro no, no significa que difieran: eso lo dice la interaccion"),
    ("Usa una covariable continua como predictor",
     "Necesita unos 10 estudios por covariable",
     "Compara entre estudios, no dentro de ellos",
     "Meta-regresion",
     "la meta-regresion correlaciona promedios de estudios: sugiere hipotesis, no las prueba"),
    ("Repite el analisis quitando un estudio cada vez",
     "Revela si el resultado depende de un solo paper",
     "Es analisis de sensibilidad, no de significacion",
     "Leave-one-out",
     "un resultado que se cae al quitar un estudio no era un resultado, era ese estudio"),
  ]),
  ("SESGO DE PUBLICACION", [
    ("Efecto en el eje X, precision en el eje Y",
     "Se espera un embudo simetrico",
     "Los estudios pequenos se dispersan en la base",
     "Funnel plot",
     "el embudo se estrecha arriba porque los estudios grandes tienen menos donde equivocarse"),
    ("Test de regresion sobre la asimetria del embudo",
     "Requiere al menos 10 estudios",
     "Da falsos positivos cuando la medida es un OR",
     "Test de Egger",
     "Egger mide si los estudios pequenos se salen del embudo hacia un lado"),
    ("Version del test pensada para desenlaces binarios",
     "Evita el falso positivo que Egger tiene con OR",
     "Tambien pide k de al menos 10",
     "Test de Peters",
     "para binarios usa Peters: Egger confunde asimetria real con artefacto matematico del OR"),
    ("Rellena el embudo con los estudios que faltarian",
     "Recalcula el efecto con esos estudios imaginarios",
     "Se reporta como sensibilidad, nunca como resultado principal",
     "Trim-and-fill",
     "trim-and-fill no corrige el sesgo, te ensena cuanto podria estar costandote"),
    ("Puede deberse a heterogeneidad real",
     "O a que los estudios pequenos se hacen peor",
     "O simplemente al azar con pocos estudios",
     "Asimetria no es igual a sesgo de publicacion",
     "un embudo torcido abre una investigacion, no cierra un diagnostico"),
  ]),
]
