# -*- coding: utf-8 -*-
# CAPA 3 de 3 del sistema de meta-analisis: R y ejecucion.
# Fuente: Harrer et al., "Doing Meta-Analysis with R" (caps. 2 R, 4-5 pooling,
# 6 forest, 9 sesgo de publicacion, 15 RoB plots, 16 reproducibilidad),
# paquete meta (Schwarzer), metafor (Viechtbauer), robvis, PRISMA2020.
# OJO: en las tarjetas el operador de asignacion va como &lt;- (entidad HTML).
NAME = "Research - Capa 3 R"

# EJE CLINICO: del PROBLEMA (en voz del que aprende) al concepto que nace.
EJES = [
  ("Vengo de Python y no se escribir R basico", [
    ("Asignar un valor a un nombre",
     "x &lt;- 5   (el = tambien funciona, pero &lt;- es la convencion)"),
    ("Crear una lista de valores del mismo tipo",
     "c(1, 2, 3)   - la c es de 'combine'"),
    ("La tabla equivalente al DataFrame de pandas",
     "data.frame  (o tibble si usas tidyverse)"),
    ("Sacar una columna por nombre",
     "df$edad   - el $ es el equivalente de df['edad']"),
    ("Sacar por posicion fila y columna",
     "df[1, 2]   - OJO: R empieza a contar en 1, no en 0"),
    ("Cargar un paquete ya instalado",
     "library(meta)"),
    ("Instalar un paquete de CRAN",
     "install.packages('meta')"),
    ("Instalar un paquete que solo esta en GitHub",
     "remotes::install_github('MathiasHarrer/dmetar')"),
  ]),
  ("Quiero meter mis datos de extraccion en R", [
    ("Leer el CSV con R base",
     "df &lt;- read.csv('extraccion/extraction.csv')"),
    ("Leerlo con tidyverse (respeta mejor los tipos)",
     "df &lt;- readr::read_csv(...)"),
    ("Ver las primeras filas",
     "head(df)"),
    ("Ver estructura, tipos y dimensiones",
     "str(df)   /   dplyr::glimpse(df)"),
    ("El valor faltante en R",
     "NA   (no es None ni NaN)"),
    ("Quedarme con las filas de un desenlace",
     "subset(df, outcome == 'mortalidad')"),
    ("Que columnas necesita un meta-analisis de binarios",
     "event.e, n.e, event.c, n.c  (eventos y n de cada brazo)"),
    ("Que columnas necesita uno de continuos",
     "n.e, mean.e, sd.e, n.c, mean.c, sd.c"),
  ]),
  ("Tengo que elegir la funcion del paquete meta", [
    ("Desenlace binario con tabla 2x2",
     "metabin()"),
    ("Desenlace continuo con media y DE",
     "metacont()"),
    ("Ya tengo el efecto y su error estandar calculados (p. ej. HR)",
     "metagen()"),
    ("Una sola proporcion o prevalencia agrupada",
     "metaprop()"),
    ("Una correlacion agrupada",
     "metacor()"),
    ("Comparaciones indirectas entre varios tratamientos",
     "netmeta()  (paquete netmeta)"),
  ]),
  ("Necesito escribir la llamada completa de metabin", [
    ("El esqueleto de la llamada",
     "m &lt;- metabin(event.e, n.e, event.c, n.c, data = df, studlab = autor)"),
    ("Elegir la medida de efecto",
     "sm = 'RR'   (o 'OR', 'RD')"),
    ("Elegir el metodo de ponderacion",
     "method = 'MH'   (Mantel-Haenszel)"),
    ("Elegir el estimador de tau cuadrado",
     "method.tau = 'REML'   (o 'PM' para binarios)"),
    ("Activar el ajuste para k pequeno",
     "method.random.ci = 'HK'   (Hartung-Knapp; en versiones antiguas hakn = TRUE)"),
    ("Pedir que se muestre solo el modelo aleatorio",
     "random = TRUE, common = FALSE"),
    ("Ver el resultado completo",
     "summary(m)"),
  ]),
  ("Necesito escribir la llamada de metacont", [
    ("El esqueleto",
     "m &lt;- metacont(n.e, mean.e, sd.e, n.c, mean.c, sd.c, data = df, studlab = autor)"),
    ("Escalas distintas entre estudios",
     "sm = 'SMD'"),
    ("Misma escala en todos",
     "sm = 'MD'"),
    ("Pedir Hedges g en vez de Cohen d",
     "method.smd = 'Hedges'  (es el default)"),
  ]),
  ("Solo tengo el efecto y su IC (tipico con HR)", [
    ("Calcular el efecto en escala log",
     "TE &lt;- log(df$hr)"),
    ("Calcular el error estandar desde el IC95%",
     "seTE &lt;- (log(df$ci_high) - log(df$ci_low)) / 3.92"),
    ("Agrupar con esos dos vectores",
     "m &lt;- metagen(TE, seTE, studlab = autor, sm = 'HR')"),
    ("Por que se pasa a log primero",
     "los ratios son asimetricos; metagen exponencia al reportar"),
  ]),
  ("Corri el modelo y no se leer la salida", [
    ("La linea que da el efecto agrupado y su IC",
     "'Random effects model' con su estimacion y IC95%"),
    ("La columna que dice cuanto pesa cada estudio",
     "%W(random)   (y %W(common) si pediste fijo)"),
    ("Donde salen los indices de heterogeneidad",
     "el bloque 'Quantifying heterogeneity': tau^2, I^2 y su IC, Q y su p"),
    ("Donde sale el intervalo de prediccion",
     "'Prediction interval' - hay que pedirlo con prediction = TRUE"),
    ("Que hay que copiar al manuscrito",
     "efecto (IC95%), k, n total, I&sup2;, &tau;&sup2;, p de Q, modelo y estimador usados"),
  ]),
  ("Quiero el forest plot publicable", [
    ("La llamada minima",
     "forest(m)"),
    ("Anadir columnas a la izquierda",
     "leftcols = c('studlab', 'event.e', 'n.e', 'event.c', 'n.c')"),
    ("Anadir efecto, IC y peso a la derecha",
     "rightcols = c('effect', 'ci', 'w.random')"),
    ("Partir el grafico por subgrupos",
     "subgroup = df$region   (antes se llamaba byvar)"),
    ("Mostrar el intervalo de prediccion como barra",
     "prediction = TRUE"),
    ("Guardarlo a 300 dpi para la revista",
     "png('forest.png', width=10, height=6, units='in', res=300); forest(m); dev.off()"),
  ]),
  ("Quiero los graficos de diagnostico", [
    ("Ver el embudo",
     "funnel(m)"),
    ("Testear la asimetria en continuos",
     "metabias(m, method.bias = 'linreg')   (Egger)"),
    ("Testear la asimetria en binarios",
     "metabias(m, method.bias = 'peters')"),
    ("Simular los estudios que faltarian",
     "trimfill(m)"),
    ("Analisis de influencia quitando un estudio cada vez",
     "metainf(m, pooled = 'random')"),
    ("Ver que estudio infla mas la heterogeneidad",
     "baujat(m)"),
    ("Detectar outliers e influencia de forma sistematica",
     "dmetar::find.outliers(m)  y  dmetar::InfluenceAnalysis(m)"),
  ]),
  ("Tengo que dibujar el riesgo de sesgo y el diagrama PRISMA", [
    ("El paquete de figuras de riesgo de sesgo",
     "robvis"),
    ("El semaforo estudio por estudio",
     "rob_traffic_light(data = rob_df, tool = 'ROB2')"),
    ("Las barras apiladas por dominio",
     "rob_summary(data = rob_df, tool = 'ROB2')"),
    ("Que herramientas admite robvis",
     "ROB2, ROBINS-I y QUADAS-2"),
    ("Que forma tiene que tener el CSV que come robvis",
     "una fila por estudio, una columna por dominio, mas Overall y Weight"),
    ("El paquete del diagrama de flujo",
     "PRISMA2020::PRISMA_flowdiagram()   a partir de un CSV de conteos"),
  ]),
  ("Quiero que esto sea reproducible", [
    ("Congelar las versiones de los paquetes del proyecto",
     "renv::init()  y  renv::snapshot()"),
    ("El documento que mezcla texto, codigo y figuras",
     "Quarto (.qmd) - exporta a Word, PDF y HTML"),
    ("Esconder el codigo pero mostrar la figura",
     "en el chunk: #| echo: false"),
    ("Poner titulo a la figura para la revista",
     "#| fig-cap: 'Forest plot de mortalidad a 30 dias'"),
    ("Fijar la aleatoriedad de un remuestreo",
     "set.seed(42)"),
    ("Ver que versiones usaste, para el apartado de metodos",
     "sessionInfo()"),
  ]),
]

# INTEGRADOR: de las SENALES al concepto + como verbalizarlo.
ESTACIONES = [
  ("R MINIMO", [
    ("Es el operador que usa todo el mundo en R para asignar",
     "El = funciona pero se reserva para argumentos de funcion",
     "Se lee 'mete esto en aquello'",
     "&lt;-",
     "en R el = habla dentro de las funciones y el &lt;- habla fuera"),
    ("Empieza a contar en 1, no en 0",
     "df[1, ] es la PRIMERA fila",
     "Es la trampa numero uno para quien viene de Python",
     "Indexacion base 1",
     "en R el primer elemento es el 1: no restes uno mentalmente, reeduca el reflejo"),
    ("Es el equivalente de df['columna'] de pandas",
     "Devuelve un vector, no una tabla",
     "Se encadena: df$col[3]",
     "El operador $",
     "el dolar de R hace lo que los corchetes en pandas: saca una columna por nombre"),
    ("No es None ni NaN ni cadena vacia",
     "Contamina cualquier operacion que lo toque",
     "Se maneja con na.rm = TRUE o is.na()",
     "NA",
     "NA no es un valor, es la ausencia de valor: por eso cualquier cuenta con NA da NA"),
  ]),
  ("ELEGIR LA FUNCION", [
    ("Recibe eventos y n de cada brazo",
     "Trabaja directo sobre la tabla 2x2",
     "Admite sm igual a RR, OR o RD",
     "metabin()",
     "si puedes contar cuantos y de cuantos en cada brazo, tu funcion es metabin"),
    ("Recibe n, media y desviacion estandar de cada brazo",
     "Admite sm igual a MD o SMD",
     "Por defecto calcula Hedges g",
     "metacont()",
     "si el desenlace es un numero en una escala, tu funcion es metacont"),
    ("No recibe datos crudos sino el efecto ya calculado",
     "Necesita TE y seTE, ambos en escala log si es un ratio",
     "Es la salida obligada para hazard ratios",
     "metagen()",
     "metagen es el ultimo recurso: entra cuando el paper te dio el resultado y no los datos"),
    ("Agrupa una sola proporcion, sin grupo de comparacion",
     "Sirve para prevalencia o para tasa de eventos adversos",
     "Suele necesitar transformacion logit o doble arcoseno",
     "metaprop()",
     "cuando no comparas nada y solo quieres el cuanto, es metaprop"),
  ]),
  ("LOS ARGUMENTOS QUE DECIDEN EL RESULTADO", [
    ("Decide si el resultado sale como RR, OR, RD, MD o SMD",
     "Es una decision de la capa 1, no de programacion",
     "Cambiarlo cambia el numero que publicas",
     "sm",
     "sm es donde tu decision sobre el diseno del estudio entra al codigo"),
    ("Elige entre DL, REML y PM",
     "Controla como se estima la varianza entre estudios",
     "El default moderno recomendado es REML",
     "method.tau",
     "method.tau no cambia el promedio, cambia cuanta desconfianza le metes al promedio"),
    ("Usa una distribucion t en lugar de la normal",
     "Ensancha el intervalo de confianza",
     "Casi obligatorio cuando tienes entre 5 y 15 estudios",
     "method.random.ci = 'HK'",
     "Hartung-Knapp es el argumento que evita publicar un IC falsamente estrecho"),
    ("Decide si se imprime el modelo fijo, el aleatorio o los dos",
     "En clinica el principal suele ser el aleatorio",
     "Se pone random = TRUE, common = FALSE",
     "random y common",
     "elige el modelo en el protocolo y luego dile a R que muestre solo ese"),
  ]),
  ("LEER LA SALIDA", [
    ("Es la columna que dice cuanto manda cada estudio",
     "Suma 100 entre todos",
     "Con efectos aleatorios esta mas aplanada",
     "%W(random)",
     "mira los pesos antes que el diamante: te dicen de quien es realmente el resultado"),
    ("Aparece en el bloque Quantifying heterogeneity",
     "Trae tambien su propio intervalo de confianza",
     "Con pocos estudios ese intervalo es enorme",
     "I&sup2; con IC",
     "un I cuadrado de 60% con IC de 0 a 90% no te esta diciendo casi nada"),
    ("Hay que pedirlo explicitamente con prediction = TRUE",
     "Es mucho mas ancho que el IC del efecto",
     "Dice donde caeria un estudio futuro",
     "Intervalo de prediccion",
     "el IC habla del promedio; el intervalo de prediccion habla del proximo estudio real"),
  ]),
  ("FIGURAS", [
    ("Se controla con leftcols y rightcols",
     "Admite subgroup para partirlo por estratos",
     "Es la figura 1 de casi todos los meta-analisis",
     "forest(m)",
     "el forest plot es la tabla de resultados y el resumen visual a la vez"),
    ("Pone el efecto en X y la precision en Y",
     "Se lee buscando simetria",
     "Solo tiene sentido interpretarlo con k de al menos 10",
     "funnel(m)",
     "con menos de diez estudios el embudo es una mancha, no una figura"),
    ("Repite el modelo omitiendo un estudio cada vez",
     "Sale una lista de efectos recalculados",
     "Se usa como analisis de sensibilidad",
     "metainf(m)",
     "si tu conclusion cambia al quitar un estudio, la conclusion era ese estudio"),
    ("Lee un CSV de dominios de riesgo de sesgo",
     "Dibuja un semaforo por estudio y dominio",
     "Admite ROB2, ROBINS-I y QUADAS-2",
     "robvis::rob_traffic_light()",
     "robvis convierte tu tabla de juicios en la figura que el revisor espera ver"),
  ]),
  ("REPRODUCIBILIDAD", [
    ("Guarda que version de cada paquete usaste",
     "Crea un archivo de bloqueo en el proyecto",
     "Permite reconstruir el entorno en otra maquina",
     "renv",
     "sin congelar versiones, 'reproducible' solo significa que funciono en tu portatil"),
    ("Mezcla texto, codigo y salida en un solo archivo",
     "Exporta a Word para mandarlo a la revista",
     "Los bloques de codigo se controlan con opciones tipo #| echo",
     "Quarto",
     "en Quarto la figura no se pega en el manuscrito: nace dentro de el"),
    ("Genera el diagrama de flujo a partir de un CSV de conteos",
     "Cumple la especificacion PRISMA 2020",
     "Tiene version interactiva para publicar en web",
     "PRISMA2020::PRISMA_flowdiagram()",
     "si el diagrama se genera del CSV, los numeros del flujo no pueden contradecir a los del texto"),
  ]),
]
